// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.358000,HLS_SYN_LAT=2282,HLS_SYN_TPT=none,HLS_SYN_MEM=33,HLS_SYN_DSP=5035,HLS_SYN_FF=106782,HLS_SYN_LUT=169920,HLS_VERSION=2019_2}" *)

module myproject (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_in_V,
        data_in_V_ap_vld,
        data_out_0_V,
        data_out_0_V_ap_vld,
        data_out_1_V,
        data_out_1_V_ap_vld,
        data_out_2_V,
        data_out_2_V_ap_vld,
        data_out_3_V,
        data_out_3_V_ap_vld,
        data_out_4_V,
        data_out_4_V_ap_vld,
        const_size_in_1,
        const_size_in_1_ap_vld,
        const_size_out_1,
        const_size_out_1_ap_vld
);

parameter    ap_ST_fsm_state1 = 35'd1;
parameter    ap_ST_fsm_state2 = 35'd2;
parameter    ap_ST_fsm_state3 = 35'd4;
parameter    ap_ST_fsm_state4 = 35'd8;
parameter    ap_ST_fsm_state5 = 35'd16;
parameter    ap_ST_fsm_state6 = 35'd32;
parameter    ap_ST_fsm_state7 = 35'd64;
parameter    ap_ST_fsm_state8 = 35'd128;
parameter    ap_ST_fsm_state9 = 35'd256;
parameter    ap_ST_fsm_state10 = 35'd512;
parameter    ap_ST_fsm_state11 = 35'd1024;
parameter    ap_ST_fsm_state12 = 35'd2048;
parameter    ap_ST_fsm_state13 = 35'd4096;
parameter    ap_ST_fsm_state14 = 35'd8192;
parameter    ap_ST_fsm_state15 = 35'd16384;
parameter    ap_ST_fsm_state16 = 35'd32768;
parameter    ap_ST_fsm_state17 = 35'd65536;
parameter    ap_ST_fsm_state18 = 35'd131072;
parameter    ap_ST_fsm_state19 = 35'd262144;
parameter    ap_ST_fsm_state20 = 35'd524288;
parameter    ap_ST_fsm_state21 = 35'd1048576;
parameter    ap_ST_fsm_state22 = 35'd2097152;
parameter    ap_ST_fsm_state23 = 35'd4194304;
parameter    ap_ST_fsm_state24 = 35'd8388608;
parameter    ap_ST_fsm_state25 = 35'd16777216;
parameter    ap_ST_fsm_state26 = 35'd33554432;
parameter    ap_ST_fsm_state27 = 35'd67108864;
parameter    ap_ST_fsm_state28 = 35'd134217728;
parameter    ap_ST_fsm_state29 = 35'd268435456;
parameter    ap_ST_fsm_state30 = 35'd536870912;
parameter    ap_ST_fsm_state31 = 35'd1073741824;
parameter    ap_ST_fsm_state32 = 35'd2147483648;
parameter    ap_ST_fsm_state33 = 35'd4294967296;
parameter    ap_ST_fsm_state34 = 35'd8589934592;
parameter    ap_ST_fsm_state35 = 35'd17179869184;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [559:0] data_in_V;
input   data_in_V_ap_vld;
output  [34:0] data_out_0_V;
output   data_out_0_V_ap_vld;
output  [34:0] data_out_1_V;
output   data_out_1_V_ap_vld;
output  [34:0] data_out_2_V;
output   data_out_2_V_ap_vld;
output  [34:0] data_out_3_V;
output   data_out_3_V_ap_vld;
output  [34:0] data_out_4_V;
output   data_out_4_V_ap_vld;
output  [15:0] const_size_in_1;
output   const_size_in_1_ap_vld;
output  [15:0] const_size_out_1;
output   const_size_out_1_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_out_0_V_ap_vld;
reg data_out_1_V_ap_vld;
reg data_out_2_V_ap_vld;
reg data_out_3_V_ap_vld;
reg data_out_4_V_ap_vld;
reg const_size_in_1_ap_vld;
reg const_size_out_1_ap_vld;

(* fsm_encoding = "none" *) reg   [34:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [559:0] data_in_V_preg;
reg   [559:0] data_in_V_in_sig;
reg    data_in_V_ap_vld_preg;
reg    data_in_V_ap_vld_in_sig;
reg    data_in_V_blk_n;
wire    ap_CS_fsm_state4;
reg   [34:0] embedded_with_cls_1_V_reg_970;
wire    ap_CS_fsm_state5;
reg   [34:0] embedded_with_cls_3_V_reg_975;
reg   [34:0] embedded_with_cls_5_V_reg_980;
reg   [34:0] embedded_with_cls_7_V_reg_985;
reg   [34:0] embedded_with_cls_9_V_reg_990;
reg   [34:0] embedded_with_cls_11_V_reg_995;
reg   [34:0] embedded_with_cls_13_V_reg_1000;
reg   [34:0] embedded_with_cls_15_V_reg_1005;
reg   [34:0] embedded_with_cls_17_V_reg_1010;
reg   [34:0] embedded_with_cls_19_V_reg_1015;
reg   [34:0] embedded_with_cls_21_V_reg_1020;
reg   [34:0] embedded_with_cls_23_V_reg_1025;
reg   [34:0] embedded_with_cls_25_V_reg_1030;
reg   [34:0] embedded_with_cls_27_V_reg_1035;
reg   [34:0] embedded_with_cls_29_V_reg_1040;
reg   [34:0] embedded_with_cls_31_V_reg_1045;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
reg   [15:0] mlp_out_red_0_V_reg_1210;
wire    ap_CS_fsm_state34;
reg   [15:0] mlp_out_red_1_V_reg_1215;
reg   [15:0] mlp_out_red_2_V_reg_1220;
reg   [15:0] mlp_out_red_3_V_reg_1225;
reg   [15:0] mlp_out_red_4_V_reg_1230;
reg   [4:0] transformer_0_out_address0;
reg    transformer_0_out_ce0;
reg    transformer_0_out_we0;
wire   [34:0] transformer_0_out_q0;
reg   [4:0] transformer_0_out_address1;
reg    transformer_0_out_ce1;
reg    transformer_0_out_we1;
wire   [34:0] transformer_0_out_q1;
reg   [3:0] mlp_dimensions_reduced_V_address0;
reg    mlp_dimensions_reduced_V_ce0;
reg    mlp_dimensions_reduced_V_we0;
wire   [34:0] mlp_dimensions_reduced_V_q0;
reg   [3:0] mlp_dimensions_reduced_V_address1;
reg    mlp_dimensions_reduced_V_ce1;
reg    mlp_dimensions_reduced_V_we1;
wire   [34:0] mlp_dimensions_reduced_V_q1;
wire    grp_transformer_fu_759_ap_start;
wire    grp_transformer_fu_759_ap_done;
wire    grp_transformer_fu_759_ap_idle;
wire    grp_transformer_fu_759_ap_ready;
wire   [4:0] grp_transformer_fu_759_res_V_address0;
wire    grp_transformer_fu_759_res_V_ce0;
wire    grp_transformer_fu_759_res_V_we0;
wire   [34:0] grp_transformer_fu_759_res_V_d0;
wire   [4:0] grp_transformer_fu_759_res_V_address1;
wire    grp_transformer_fu_759_res_V_ce1;
wire    grp_transformer_fu_759_res_V_we1;
wire   [34:0] grp_transformer_fu_759_res_V_d1;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_0;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_1;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_2;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_3;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_4;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_5;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_6;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_7;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_8;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_9;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_10;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_11;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_12;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_13;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_14;
wire   [34:0] grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_15;
wire    grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_start;
wire    grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done;
wire    grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_idle;
wire    grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_ready;
wire   [34:0] grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_0;
wire   [34:0] grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_1;
wire   [34:0] grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_2;
wire   [34:0] grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_3;
wire   [34:0] grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_4;
wire    grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_start;
wire    grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_done;
wire    grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_idle;
wire    grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_ready;
wire   [3:0] grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_address0;
wire    grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_ce0;
wire   [3:0] grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_address1;
wire    grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_ce1;
wire   [34:0] grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_0;
wire   [34:0] grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_1;
wire   [34:0] grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_2;
wire   [34:0] grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_3;
wire   [34:0] grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_4;
reg    grp_transformer_fu_759_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_start_reg;
wire    ap_CS_fsm_state35;
reg    grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_start_reg;
wire    ap_CS_fsm_state24;
reg   [34:0] ap_NS_fsm;
wire    ap_NS_fsm_state25;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;

// power-on initialization
initial begin
#0 ap_CS_fsm = 35'd1;
#0 data_in_V_preg = 560'd0;
#0 data_in_V_ap_vld_preg = 1'b0;
#0 grp_transformer_fu_759_ap_start_reg = 1'b0;
#0 grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_start_reg = 1'b0;
#0 grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_start_reg = 1'b0;
end

myproject_transformer_0_out #(
    .DataWidth( 35 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
transformer_0_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(transformer_0_out_address0),
    .ce0(transformer_0_out_ce0),
    .we0(transformer_0_out_we0),
    .d0(grp_transformer_fu_759_res_V_d0),
    .q0(transformer_0_out_q0),
    .address1(transformer_0_out_address1),
    .ce1(transformer_0_out_ce1),
    .we1(transformer_0_out_we1),
    .d1(grp_transformer_fu_759_res_V_d1),
    .q1(transformer_0_out_q1)
);

myproject_mlp_dimensions_reduced_V #(
    .DataWidth( 35 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
mlp_dimensions_reduced_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mlp_dimensions_reduced_V_address0),
    .ce0(mlp_dimensions_reduced_V_ce0),
    .we0(mlp_dimensions_reduced_V_we0),
    .d0(transformer_0_out_q0),
    .q0(mlp_dimensions_reduced_V_q0),
    .address1(mlp_dimensions_reduced_V_address1),
    .ce1(mlp_dimensions_reduced_V_ce1),
    .we1(mlp_dimensions_reduced_V_we1),
    .d1(transformer_0_out_q1),
    .q1(mlp_dimensions_reduced_V_q1)
);

transformer grp_transformer_fu_759(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_transformer_fu_759_ap_start),
    .ap_done(grp_transformer_fu_759_ap_done),
    .ap_idle(grp_transformer_fu_759_ap_idle),
    .ap_ready(grp_transformer_fu_759_ap_ready),
    .data_1_V_read(embedded_with_cls_1_V_reg_970),
    .data_3_V_read(embedded_with_cls_3_V_reg_975),
    .data_5_V_read(embedded_with_cls_5_V_reg_980),
    .data_7_V_read(embedded_with_cls_7_V_reg_985),
    .data_9_V_read(embedded_with_cls_9_V_reg_990),
    .data_11_V_read(embedded_with_cls_11_V_reg_995),
    .data_13_V_read(embedded_with_cls_13_V_reg_1000),
    .data_15_V_read(embedded_with_cls_15_V_reg_1005),
    .data_17_V_read(embedded_with_cls_17_V_reg_1010),
    .data_19_V_read(embedded_with_cls_19_V_reg_1015),
    .data_21_V_read(embedded_with_cls_21_V_reg_1020),
    .data_23_V_read(embedded_with_cls_23_V_reg_1025),
    .data_25_V_read(embedded_with_cls_25_V_reg_1030),
    .data_27_V_read(embedded_with_cls_27_V_reg_1035),
    .data_29_V_read(embedded_with_cls_29_V_reg_1040),
    .data_31_V_read(embedded_with_cls_31_V_reg_1045),
    .res_V_address0(grp_transformer_fu_759_res_V_address0),
    .res_V_ce0(grp_transformer_fu_759_res_V_ce0),
    .res_V_we0(grp_transformer_fu_759_res_V_we0),
    .res_V_d0(grp_transformer_fu_759_res_V_d0),
    .res_V_address1(grp_transformer_fu_759_res_V_address1),
    .res_V_ce1(grp_transformer_fu_759_res_V_ce1),
    .res_V_we1(grp_transformer_fu_759_res_V_we1),
    .res_V_d1(grp_transformer_fu_759_res_V_d1)
);

dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2 grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_V_read(data_in_V_in_sig),
    .ap_return_0(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_0),
    .ap_return_1(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_1),
    .ap_return_2(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_2),
    .ap_return_3(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_3),
    .ap_return_4(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_4),
    .ap_return_5(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_5),
    .ap_return_6(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_6),
    .ap_return_7(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_7),
    .ap_return_8(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_8),
    .ap_return_9(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_9),
    .ap_return_10(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_10),
    .ap_return_11(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_11),
    .ap_return_12(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_12),
    .ap_return_13(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_13),
    .ap_return_14(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_14),
    .ap_return_15(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_15)
);

log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_start),
    .ap_done(grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done),
    .ap_idle(grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_idle),
    .ap_ready(grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_ready),
    .data_0_V_read(mlp_out_red_0_V_reg_1210),
    .data_1_V_read(mlp_out_red_1_V_reg_1215),
    .data_2_V_read(mlp_out_red_2_V_reg_1220),
    .data_3_V_read(mlp_out_red_3_V_reg_1225),
    .data_4_V_read(mlp_out_red_4_V_reg_1230),
    .ap_return_0(grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_0),
    .ap_return_1(grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_1),
    .ap_return_2(grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_2),
    .ap_return_3(grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_3),
    .ap_return_4(grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_4)
);

dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0 grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_start),
    .ap_done(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_done),
    .ap_idle(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_idle),
    .ap_ready(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_ready),
    .data_V_address0(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_address0),
    .data_V_ce0(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_ce0),
    .data_V_q0(mlp_dimensions_reduced_V_q0),
    .data_V_address1(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_address1),
    .data_V_ce1(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_ce1),
    .data_V_q1(mlp_dimensions_reduced_V_q1),
    .ap_return_0(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        data_in_V_ap_vld_preg <= 1'b0;
    end else begin
        if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
            data_in_V_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (data_in_V_ap_vld == 1'b1))) begin
            data_in_V_ap_vld_preg <= data_in_V_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        data_in_V_preg <= 560'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (data_in_V_ap_vld == 1'b1))) begin
            data_in_V_preg <= data_in_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state25) & (1'b1 == ap_CS_fsm_state24))) begin
            grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_ready == 1'b1)) begin
            grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state34)) begin
            grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_start_reg <= 1'b1;
        end else if ((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_ready == 1'b1)) begin
            grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_transformer_fu_759_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_transformer_fu_759_ap_start_reg <= 1'b1;
        end else if ((grp_transformer_fu_759_ap_ready == 1'b1)) begin
            grp_transformer_fu_759_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        embedded_with_cls_11_V_reg_995 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_5;
        embedded_with_cls_13_V_reg_1000 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_6;
        embedded_with_cls_15_V_reg_1005 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_7;
        embedded_with_cls_17_V_reg_1010 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_8;
        embedded_with_cls_19_V_reg_1015 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_9;
        embedded_with_cls_1_V_reg_970 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_0;
        embedded_with_cls_21_V_reg_1020 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_10;
        embedded_with_cls_23_V_reg_1025 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_11;
        embedded_with_cls_25_V_reg_1030 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_12;
        embedded_with_cls_27_V_reg_1035 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_13;
        embedded_with_cls_29_V_reg_1040 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_14;
        embedded_with_cls_31_V_reg_1045 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_15;
        embedded_with_cls_3_V_reg_975 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_1;
        embedded_with_cls_5_V_reg_980 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_2;
        embedded_with_cls_7_V_reg_985 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_3;
        embedded_with_cls_9_V_reg_990 <= grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_2_fu_784_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        mlp_out_red_0_V_reg_1210 <= {{grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_0[25:10]}};
        mlp_out_red_1_V_reg_1215 <= {{grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_1[25:10]}};
        mlp_out_red_2_V_reg_1220 <= {{grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_2[25:10]}};
        mlp_out_red_3_V_reg_1225 <= {{grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_3[25:10]}};
        mlp_out_red_4_V_reg_1230 <= {{grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_return_4[25:10]}};
    end
end

always @ (*) begin
    if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        const_size_in_1_ap_vld = 1'b1;
    end else begin
        const_size_in_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        const_size_out_1_ap_vld = 1'b1;
    end else begin
        const_size_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((data_in_V_ap_vld == 1'b1)) begin
        data_in_V_ap_vld_in_sig = data_in_V_ap_vld;
    end else begin
        data_in_V_ap_vld_in_sig = data_in_V_ap_vld_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_in_V_blk_n = data_in_V_ap_vld;
    end else begin
        data_in_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((data_in_V_ap_vld == 1'b1)) begin
        data_in_V_in_sig = data_in_V;
    end else begin
        data_in_V_in_sig = data_in_V_preg;
    end
end

always @ (*) begin
    if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        data_out_0_V_ap_vld = 1'b1;
    end else begin
        data_out_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        data_out_1_V_ap_vld = 1'b1;
    end else begin
        data_out_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        data_out_2_V_ap_vld = 1'b1;
    end else begin
        data_out_2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        data_out_3_V_ap_vld = 1'b1;
    end else begin
        data_out_3_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        data_out_4_V_ap_vld = 1'b1;
    end else begin
        data_out_4_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        mlp_dimensions_reduced_V_address0 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        mlp_dimensions_reduced_V_address0 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        mlp_dimensions_reduced_V_address0 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        mlp_dimensions_reduced_V_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mlp_dimensions_reduced_V_address0 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        mlp_dimensions_reduced_V_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        mlp_dimensions_reduced_V_address0 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        mlp_dimensions_reduced_V_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        mlp_dimensions_reduced_V_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        mlp_dimensions_reduced_V_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        mlp_dimensions_reduced_V_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        mlp_dimensions_reduced_V_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mlp_dimensions_reduced_V_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        mlp_dimensions_reduced_V_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mlp_dimensions_reduced_V_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        mlp_dimensions_reduced_V_address0 = 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25))) begin
        mlp_dimensions_reduced_V_address0 = grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_address0;
    end else begin
        mlp_dimensions_reduced_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        mlp_dimensions_reduced_V_address1 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        mlp_dimensions_reduced_V_address1 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        mlp_dimensions_reduced_V_address1 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        mlp_dimensions_reduced_V_address1 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        mlp_dimensions_reduced_V_address1 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        mlp_dimensions_reduced_V_address1 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        mlp_dimensions_reduced_V_address1 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        mlp_dimensions_reduced_V_address1 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        mlp_dimensions_reduced_V_address1 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        mlp_dimensions_reduced_V_address1 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        mlp_dimensions_reduced_V_address1 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        mlp_dimensions_reduced_V_address1 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        mlp_dimensions_reduced_V_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        mlp_dimensions_reduced_V_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        mlp_dimensions_reduced_V_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        mlp_dimensions_reduced_V_address1 = 64'd1;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25))) begin
        mlp_dimensions_reduced_V_address1 = grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_address1;
    end else begin
        mlp_dimensions_reduced_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        mlp_dimensions_reduced_V_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25))) begin
        mlp_dimensions_reduced_V_ce0 = grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_ce0;
    end else begin
        mlp_dimensions_reduced_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        mlp_dimensions_reduced_V_ce1 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25))) begin
        mlp_dimensions_reduced_V_ce1 = grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_data_V_ce1;
    end else begin
        mlp_dimensions_reduced_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        mlp_dimensions_reduced_V_we0 = 1'b1;
    end else begin
        mlp_dimensions_reduced_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        mlp_dimensions_reduced_V_we1 = 1'b1;
    end else begin
        mlp_dimensions_reduced_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        transformer_0_out_address0 = 64'd60;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        transformer_0_out_address0 = 64'd56;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        transformer_0_out_address0 = 64'd52;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        transformer_0_out_address0 = 64'd48;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        transformer_0_out_address0 = 64'd44;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        transformer_0_out_address0 = 64'd40;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        transformer_0_out_address0 = 64'd36;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        transformer_0_out_address0 = 64'd32;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        transformer_0_out_address0 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        transformer_0_out_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        transformer_0_out_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        transformer_0_out_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        transformer_0_out_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        transformer_0_out_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        transformer_0_out_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        transformer_0_out_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        transformer_0_out_address0 = grp_transformer_fu_759_res_V_address0;
    end else begin
        transformer_0_out_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        transformer_0_out_address1 = 64'd62;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        transformer_0_out_address1 = 64'd58;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        transformer_0_out_address1 = 64'd54;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        transformer_0_out_address1 = 64'd50;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        transformer_0_out_address1 = 64'd46;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        transformer_0_out_address1 = 64'd42;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        transformer_0_out_address1 = 64'd38;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        transformer_0_out_address1 = 64'd34;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        transformer_0_out_address1 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        transformer_0_out_address1 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        transformer_0_out_address1 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        transformer_0_out_address1 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        transformer_0_out_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        transformer_0_out_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        transformer_0_out_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        transformer_0_out_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        transformer_0_out_address1 = grp_transformer_fu_759_res_V_address1;
    end else begin
        transformer_0_out_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        transformer_0_out_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        transformer_0_out_ce0 = grp_transformer_fu_759_res_V_ce0;
    end else begin
        transformer_0_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        transformer_0_out_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        transformer_0_out_ce1 = grp_transformer_fu_759_res_V_ce1;
    end else begin
        transformer_0_out_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        transformer_0_out_we0 = grp_transformer_fu_759_res_V_we0;
    end else begin
        transformer_0_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        transformer_0_out_we1 = grp_transformer_fu_759_res_V_we1;
    end else begin
        transformer_0_out_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((data_in_V_ap_vld_in_sig == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_transformer_fu_759_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            if (((grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state25 = ap_NS_fsm[32'd24];

assign const_size_in_1 = 16'd16;

assign const_size_out_1 = 16'd5;

assign data_out_0_V = grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_0;

assign data_out_1_V = grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_1;

assign data_out_2_V = grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_2;

assign data_out_3_V = grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_3;

assign data_out_4_V = grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_return_4;

assign grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_start = grp_dense_latency_ap_fixed_ap_fixed_mlp_config_0_0_0_0_0_0_fu_801_ap_start_reg;

assign grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_start = grp_log_softmax_latency_ap_fixed_ap_fixed_softmax_config0_s_fu_790_ap_start_reg;

assign grp_transformer_fu_759_ap_start = grp_transformer_fu_759_ap_start_reg;

endmodule //myproject
