// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matmul_ap_fixed_ap_fixed_2ul_2ul_2ul_8ul_s (
        ap_clk,
        ap_rst,
        a_0_0_V_read,
        a_0_1_V_read,
        a_1_0_V_read,
        a_1_1_V_read,
        a_2_0_V_read,
        a_2_1_V_read,
        a_3_0_V_read,
        a_3_1_V_read,
        a_V_offset,
        b_0_0_V_read,
        b_0_1_V_read,
        b_1_0_V_read,
        b_1_1_V_read,
        b_2_0_V_read,
        b_2_1_V_read,
        b_3_0_V_read,
        b_3_1_V_read,
        b_4_0_V_read,
        b_4_1_V_read,
        b_5_0_V_read,
        b_5_1_V_read,
        b_6_0_V_read,
        b_6_1_V_read,
        b_7_0_V_read,
        b_7_1_V_read,
        b_8_0_V_read,
        b_8_1_V_read,
        b_9_0_V_read,
        b_9_1_V_read,
        b_10_0_V_read,
        b_10_1_V_read,
        b_11_0_V_read,
        b_11_1_V_read,
        b_12_0_V_read,
        b_12_1_V_read,
        b_13_0_V_read,
        b_13_1_V_read,
        b_14_0_V_read,
        b_14_1_V_read,
        b_15_0_V_read,
        b_15_1_V_read,
        b_V_offset,
        res_0_0_V_read_4,
        res_0_0_V_read,
        res_0_1_V_read_4,
        res_0_1_V_read,
        res_1_0_V_read_4,
        res_1_0_V_read,
        res_1_1_V_read_4,
        res_1_1_V_read,
        res_2_0_V_read_4,
        res_2_0_V_read,
        res_2_1_V_read_4,
        res_2_1_V_read,
        res_3_0_V_read_4,
        res_3_0_V_read,
        res_3_1_V_read_4,
        res_3_1_V_read,
        res_4_0_V_read_2,
        res_4_0_V_read,
        res_4_1_V_read_2,
        res_4_1_V_read,
        res_5_0_V_read_2,
        res_5_0_V_read,
        res_5_1_V_read_2,
        res_5_1_V_read,
        res_6_0_V_read_2,
        res_6_0_V_read,
        res_6_1_V_read_2,
        res_6_1_V_read,
        res_7_0_V_read_2,
        res_7_0_V_read,
        res_7_1_V_read_2,
        res_7_1_V_read,
        res_8_0_V_read_2,
        res_8_0_V_read,
        res_8_1_V_read_2,
        res_8_1_V_read,
        res_9_0_V_read_2,
        res_9_0_V_read,
        res_9_1_V_read_2,
        res_9_1_V_read,
        res_10_0_V_read_2,
        res_10_0_V_read,
        res_10_1_V_read_2,
        res_10_1_V_read,
        res_11_0_V_read_2,
        res_11_0_V_read,
        res_11_1_V_read_2,
        res_11_1_V_read,
        res_12_0_V_read_2,
        res_12_0_V_read,
        res_12_1_V_read_2,
        res_12_1_V_read,
        res_13_0_V_read_2,
        res_13_0_V_read,
        res_13_1_V_read_2,
        res_13_1_V_read,
        res_14_0_V_read_2,
        res_14_0_V_read,
        res_14_1_V_read_2,
        res_14_1_V_read,
        res_15_0_V_read_2,
        res_15_0_V_read,
        res_15_1_V_read_2,
        res_15_1_V_read,
        res_V_offset,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [34:0] a_0_0_V_read;
input  [34:0] a_0_1_V_read;
input  [34:0] a_1_0_V_read;
input  [34:0] a_1_1_V_read;
input  [34:0] a_2_0_V_read;
input  [34:0] a_2_1_V_read;
input  [34:0] a_3_0_V_read;
input  [34:0] a_3_1_V_read;
input  [0:0] a_V_offset;
input  [34:0] b_0_0_V_read;
input  [34:0] b_0_1_V_read;
input  [34:0] b_1_0_V_read;
input  [34:0] b_1_1_V_read;
input  [34:0] b_2_0_V_read;
input  [34:0] b_2_1_V_read;
input  [34:0] b_3_0_V_read;
input  [34:0] b_3_1_V_read;
input  [34:0] b_4_0_V_read;
input  [34:0] b_4_1_V_read;
input  [34:0] b_5_0_V_read;
input  [34:0] b_5_1_V_read;
input  [34:0] b_6_0_V_read;
input  [34:0] b_6_1_V_read;
input  [34:0] b_7_0_V_read;
input  [34:0] b_7_1_V_read;
input  [34:0] b_8_0_V_read;
input  [34:0] b_8_1_V_read;
input  [34:0] b_9_0_V_read;
input  [34:0] b_9_1_V_read;
input  [34:0] b_10_0_V_read;
input  [34:0] b_10_1_V_read;
input  [34:0] b_11_0_V_read;
input  [34:0] b_11_1_V_read;
input  [34:0] b_12_0_V_read;
input  [34:0] b_12_1_V_read;
input  [34:0] b_13_0_V_read;
input  [34:0] b_13_1_V_read;
input  [34:0] b_14_0_V_read;
input  [34:0] b_14_1_V_read;
input  [34:0] b_15_0_V_read;
input  [34:0] b_15_1_V_read;
input  [0:0] b_V_offset;
input  [34:0] res_0_0_V_read_4;
input  [34:0] res_0_0_V_read;
input  [34:0] res_0_1_V_read_4;
input  [34:0] res_0_1_V_read;
input  [34:0] res_1_0_V_read_4;
input  [34:0] res_1_0_V_read;
input  [34:0] res_1_1_V_read_4;
input  [34:0] res_1_1_V_read;
input  [34:0] res_2_0_V_read_4;
input  [34:0] res_2_0_V_read;
input  [34:0] res_2_1_V_read_4;
input  [34:0] res_2_1_V_read;
input  [34:0] res_3_0_V_read_4;
input  [34:0] res_3_0_V_read;
input  [34:0] res_3_1_V_read_4;
input  [34:0] res_3_1_V_read;
input  [34:0] res_4_0_V_read_2;
input  [34:0] res_4_0_V_read;
input  [34:0] res_4_1_V_read_2;
input  [34:0] res_4_1_V_read;
input  [34:0] res_5_0_V_read_2;
input  [34:0] res_5_0_V_read;
input  [34:0] res_5_1_V_read_2;
input  [34:0] res_5_1_V_read;
input  [34:0] res_6_0_V_read_2;
input  [34:0] res_6_0_V_read;
input  [34:0] res_6_1_V_read_2;
input  [34:0] res_6_1_V_read;
input  [34:0] res_7_0_V_read_2;
input  [34:0] res_7_0_V_read;
input  [34:0] res_7_1_V_read_2;
input  [34:0] res_7_1_V_read;
input  [34:0] res_8_0_V_read_2;
input  [34:0] res_8_0_V_read;
input  [34:0] res_8_1_V_read_2;
input  [34:0] res_8_1_V_read;
input  [34:0] res_9_0_V_read_2;
input  [34:0] res_9_0_V_read;
input  [34:0] res_9_1_V_read_2;
input  [34:0] res_9_1_V_read;
input  [34:0] res_10_0_V_read_2;
input  [34:0] res_10_0_V_read;
input  [34:0] res_10_1_V_read_2;
input  [34:0] res_10_1_V_read;
input  [34:0] res_11_0_V_read_2;
input  [34:0] res_11_0_V_read;
input  [34:0] res_11_1_V_read_2;
input  [34:0] res_11_1_V_read;
input  [34:0] res_12_0_V_read_2;
input  [34:0] res_12_0_V_read;
input  [34:0] res_12_1_V_read_2;
input  [34:0] res_12_1_V_read;
input  [34:0] res_13_0_V_read_2;
input  [34:0] res_13_0_V_read;
input  [34:0] res_13_1_V_read_2;
input  [34:0] res_13_1_V_read;
input  [34:0] res_14_0_V_read_2;
input  [34:0] res_14_0_V_read;
input  [34:0] res_14_1_V_read_2;
input  [34:0] res_14_1_V_read;
input  [34:0] res_15_0_V_read_2;
input  [34:0] res_15_0_V_read;
input  [34:0] res_15_1_V_read_2;
input  [34:0] res_15_1_V_read;
input  [0:0] res_V_offset;
output  [34:0] ap_return_0;
output  [34:0] ap_return_1;
output  [34:0] ap_return_2;
output  [34:0] ap_return_3;
output  [34:0] ap_return_4;
output  [34:0] ap_return_5;
output  [34:0] ap_return_6;
output  [34:0] ap_return_7;
output  [34:0] ap_return_8;
output  [34:0] ap_return_9;
output  [34:0] ap_return_10;
output  [34:0] ap_return_11;
output  [34:0] ap_return_12;
output  [34:0] ap_return_13;
output  [34:0] ap_return_14;
output  [34:0] ap_return_15;
output  [34:0] ap_return_16;
output  [34:0] ap_return_17;
output  [34:0] ap_return_18;
output  [34:0] ap_return_19;
output  [34:0] ap_return_20;
output  [34:0] ap_return_21;
output  [34:0] ap_return_22;
output  [34:0] ap_return_23;
output  [34:0] ap_return_24;
output  [34:0] ap_return_25;
output  [34:0] ap_return_26;
output  [34:0] ap_return_27;
output  [34:0] ap_return_28;
output  [34:0] ap_return_29;
output  [34:0] ap_return_30;
output  [34:0] ap_return_31;
input   ap_ce;

reg[34:0] ap_return_0;
reg[34:0] ap_return_1;
reg[34:0] ap_return_2;
reg[34:0] ap_return_3;
reg[34:0] ap_return_4;
reg[34:0] ap_return_5;
reg[34:0] ap_return_6;
reg[34:0] ap_return_7;
reg[34:0] ap_return_8;
reg[34:0] ap_return_9;
reg[34:0] ap_return_10;
reg[34:0] ap_return_11;
reg[34:0] ap_return_12;
reg[34:0] ap_return_13;
reg[34:0] ap_return_14;
reg[34:0] ap_return_15;
reg[34:0] ap_return_16;
reg[34:0] ap_return_17;
reg[34:0] ap_return_18;
reg[34:0] ap_return_19;
reg[34:0] ap_return_20;
reg[34:0] ap_return_21;
reg[34:0] ap_return_22;
reg[34:0] ap_return_23;
reg[34:0] ap_return_24;
reg[34:0] ap_return_25;
reg[34:0] ap_return_26;
reg[34:0] ap_return_27;
reg[34:0] ap_return_28;
reg[34:0] ap_return_29;
reg[34:0] ap_return_30;
reg[34:0] ap_return_31;

reg   [0:0] res_V_offset_read_reg_2966;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [34:0] res_15_1_V_read_4_reg_3002;
reg   [34:0] res_15_0_V_read_4_reg_3007;
reg   [34:0] res_14_1_V_read_4_reg_3012;
reg   [34:0] res_14_0_V_read_4_reg_3017;
reg   [34:0] res_13_1_V_read_3_reg_3022;
reg   [34:0] res_13_0_V_read_4_reg_3027;
reg   [34:0] res_12_1_V_read_4_reg_3032;
reg   [34:0] res_12_0_V_read_4_reg_3037;
reg   [34:0] res_11_1_V_read_4_reg_3042;
reg   [34:0] res_11_0_V_read_3_reg_3047;
reg   [34:0] res_10_1_V_read_4_reg_3052;
reg   [34:0] res_10_0_V_read_4_reg_3057;
reg   [34:0] res_9_1_V_read_4_reg_3062;
reg   [34:0] res_9_0_V_read_4_reg_3067;
reg   [34:0] res_8_1_V_read_3_reg_3072;
reg   [34:0] res_8_0_V_read_4_reg_3077;
reg   [34:0] res_7_1_V_read_4_reg_3082;
reg   [34:0] res_7_0_V_read_4_reg_3087;
reg   [34:0] res_6_1_V_read_4_reg_3092;
reg   [34:0] res_6_0_V_read_3_reg_3097;
reg   [34:0] res_5_1_V_read_4_reg_3102;
reg   [34:0] res_5_0_V_read_4_reg_3107;
reg   [34:0] res_4_1_V_read_4_reg_3112;
reg   [34:0] res_4_0_V_read_4_reg_3117;
reg   [34:0] res_3_1_V_read_5_reg_3122;
reg   [34:0] res_3_0_V_read_6_reg_3127;
reg   [34:0] res_2_1_V_read_6_reg_3132;
reg   [34:0] res_2_0_V_read_6_reg_3137;
reg   [34:0] res_1_1_V_read_5_reg_3142;
reg   [34:0] res_1_0_V_read_5_reg_3147;
reg   [34:0] res_0_1_V_read_6_reg_3152;
reg   [34:0] res_0_0_V_read_6_reg_3157;
wire   [31:0] select_ln1116_17_fu_1654_p3;
reg   [31:0] select_ln1116_17_reg_3162;
wire   [34:0] select_ln1117_23_fu_1662_p3;
reg   [34:0] select_ln1117_23_reg_3167;
reg   [34:0] tmp_reg_3172;
wire  signed [31:0] select_ln1116_18_fu_1688_p3;
reg  signed [31:0] select_ln1116_18_reg_3177;
reg   [34:0] tmp_s_reg_3183;
wire   [34:0] select_ln1117_24_fu_1706_p3;
reg   [34:0] select_ln1117_24_reg_3188;
reg   [34:0] tmp_27_reg_3193;
reg   [34:0] tmp_28_reg_3198;
wire   [34:0] select_ln1117_25_fu_1734_p3;
reg   [34:0] select_ln1117_25_reg_3203;
reg   [34:0] tmp_29_reg_3208;
reg   [34:0] tmp_30_reg_3213;
wire   [34:0] select_ln1117_26_fu_1762_p3;
reg   [34:0] select_ln1117_26_reg_3218;
reg   [34:0] tmp_31_reg_3223;
reg   [34:0] tmp_32_reg_3228;
wire   [34:0] select_ln1117_27_fu_1790_p3;
reg   [34:0] select_ln1117_27_reg_3233;
reg   [34:0] tmp_33_reg_3238;
reg   [34:0] tmp_34_reg_3243;
wire   [34:0] select_ln1117_28_fu_1818_p3;
reg   [34:0] select_ln1117_28_reg_3248;
reg   [34:0] tmp_35_reg_3253;
reg   [34:0] tmp_36_reg_3258;
wire   [34:0] select_ln1117_29_fu_1846_p3;
reg   [34:0] select_ln1117_29_reg_3263;
reg   [34:0] tmp_37_reg_3268;
reg   [34:0] tmp_38_reg_3273;
wire  signed [34:0] select_ln1117_30_fu_1874_p3;
reg  signed [34:0] select_ln1117_30_reg_3278;
reg   [34:0] tmp_39_reg_3284;
reg   [34:0] tmp_40_reg_3289;
wire    ap_block_pp0_stage0;
wire   [31:0] trunc_ln1116_fu_874_p1;
wire   [31:0] trunc_ln1116_1_fu_878_p1;
wire   [31:0] select_ln1116_fu_882_p3;
wire   [34:0] select_ln1117_fu_894_p3;
wire  signed [31:0] mul_ln1118_fu_906_p0;
wire  signed [66:0] sext_ln1117_fu_890_p1;
wire  signed [34:0] mul_ln1118_fu_906_p1;
wire  signed [66:0] sext_ln1118_fu_902_p1;
wire   [66:0] mul_ln1118_fu_906_p2;
wire   [34:0] select_ln1265_fu_916_p3;
wire   [54:0] shl_ln_fu_924_p3;
wire  signed [69:0] sext_ln1118_36_fu_912_p1;
wire   [70:0] zext_ln728_fu_932_p1;
wire   [70:0] zext_ln703_fu_936_p1;
wire   [31:0] trunc_ln1116_2_fu_946_p1;
wire   [31:0] trunc_ln1116_3_fu_950_p1;
wire  signed [31:0] select_ln1116_16_fu_954_p3;
wire  signed [31:0] mul_ln1118_28_fu_966_p0;
wire  signed [66:0] sext_ln1118_37_fu_962_p1;
wire  signed [34:0] mul_ln1118_28_fu_966_p1;
wire   [66:0] mul_ln1118_28_fu_966_p2;
wire   [34:0] select_ln1265_4_fu_976_p3;
wire   [54:0] shl_ln728_s_fu_984_p3;
wire  signed [69:0] sext_ln1118_38_fu_972_p1;
wire   [70:0] zext_ln728_24_fu_992_p1;
wire   [70:0] zext_ln703_24_fu_996_p1;
wire   [34:0] select_ln1117_16_fu_1006_p3;
wire  signed [31:0] mul_ln1118_29_fu_1018_p0;
wire  signed [34:0] mul_ln1118_29_fu_1018_p1;
wire  signed [66:0] sext_ln1118_39_fu_1014_p1;
wire   [66:0] mul_ln1118_29_fu_1018_p2;
wire   [34:0] select_ln1265_5_fu_1028_p3;
wire   [54:0] shl_ln728_31_fu_1036_p3;
wire  signed [69:0] sext_ln1118_40_fu_1024_p1;
wire   [70:0] zext_ln728_25_fu_1044_p1;
wire   [70:0] zext_ln703_25_fu_1048_p1;
wire  signed [31:0] mul_ln1118_30_fu_1058_p0;
wire  signed [34:0] mul_ln1118_30_fu_1058_p1;
wire   [66:0] mul_ln1118_30_fu_1058_p2;
wire   [34:0] select_ln1265_6_fu_1068_p3;
wire   [54:0] shl_ln728_32_fu_1076_p3;
wire  signed [69:0] sext_ln1118_41_fu_1064_p1;
wire   [70:0] zext_ln728_26_fu_1084_p1;
wire   [70:0] zext_ln703_26_fu_1088_p1;
wire   [34:0] select_ln1117_17_fu_1098_p3;
wire  signed [31:0] mul_ln1118_31_fu_1110_p0;
wire  signed [34:0] mul_ln1118_31_fu_1110_p1;
wire  signed [66:0] sext_ln1118_42_fu_1106_p1;
wire   [66:0] mul_ln1118_31_fu_1110_p2;
wire   [34:0] select_ln1265_7_fu_1120_p3;
wire   [54:0] shl_ln728_33_fu_1128_p3;
wire  signed [69:0] sext_ln1118_43_fu_1116_p1;
wire   [70:0] zext_ln728_27_fu_1136_p1;
wire   [70:0] zext_ln703_27_fu_1140_p1;
wire  signed [31:0] mul_ln1118_32_fu_1150_p0;
wire  signed [34:0] mul_ln1118_32_fu_1150_p1;
wire   [66:0] mul_ln1118_32_fu_1150_p2;
wire   [34:0] select_ln1265_8_fu_1160_p3;
wire   [54:0] shl_ln728_34_fu_1168_p3;
wire  signed [69:0] sext_ln1118_44_fu_1156_p1;
wire   [70:0] zext_ln728_28_fu_1176_p1;
wire   [70:0] zext_ln703_28_fu_1180_p1;
wire   [34:0] select_ln1117_18_fu_1190_p3;
wire  signed [31:0] mul_ln1118_33_fu_1202_p0;
wire  signed [34:0] mul_ln1118_33_fu_1202_p1;
wire  signed [66:0] sext_ln1118_45_fu_1198_p1;
wire   [66:0] mul_ln1118_33_fu_1202_p2;
wire   [34:0] select_ln1265_9_fu_1212_p3;
wire   [54:0] shl_ln728_35_fu_1220_p3;
wire  signed [69:0] sext_ln1118_46_fu_1208_p1;
wire   [70:0] zext_ln728_29_fu_1228_p1;
wire   [70:0] zext_ln703_29_fu_1232_p1;
wire  signed [31:0] mul_ln1118_34_fu_1242_p0;
wire  signed [34:0] mul_ln1118_34_fu_1242_p1;
wire   [66:0] mul_ln1118_34_fu_1242_p2;
wire   [34:0] select_ln1265_10_fu_1252_p3;
wire   [54:0] shl_ln728_36_fu_1260_p3;
wire  signed [69:0] sext_ln1118_47_fu_1248_p1;
wire   [70:0] zext_ln728_30_fu_1268_p1;
wire   [70:0] zext_ln703_30_fu_1272_p1;
wire   [34:0] select_ln1117_19_fu_1282_p3;
wire  signed [31:0] mul_ln1118_35_fu_1294_p0;
wire  signed [34:0] mul_ln1118_35_fu_1294_p1;
wire  signed [66:0] sext_ln1118_48_fu_1290_p1;
wire   [66:0] mul_ln1118_35_fu_1294_p2;
wire   [34:0] select_ln1265_11_fu_1304_p3;
wire   [54:0] shl_ln728_37_fu_1312_p3;
wire  signed [69:0] sext_ln1118_49_fu_1300_p1;
wire   [70:0] zext_ln728_31_fu_1320_p1;
wire   [70:0] zext_ln703_31_fu_1324_p1;
wire  signed [31:0] mul_ln1118_36_fu_1334_p0;
wire  signed [34:0] mul_ln1118_36_fu_1334_p1;
wire   [66:0] mul_ln1118_36_fu_1334_p2;
wire   [34:0] select_ln1265_12_fu_1344_p3;
wire   [54:0] shl_ln728_38_fu_1352_p3;
wire  signed [69:0] sext_ln1118_50_fu_1340_p1;
wire   [70:0] zext_ln728_32_fu_1360_p1;
wire   [70:0] zext_ln703_32_fu_1364_p1;
wire   [34:0] select_ln1117_20_fu_1374_p3;
wire  signed [31:0] mul_ln1118_37_fu_1386_p0;
wire  signed [34:0] mul_ln1118_37_fu_1386_p1;
wire  signed [66:0] sext_ln1118_51_fu_1382_p1;
wire   [66:0] mul_ln1118_37_fu_1386_p2;
wire   [34:0] select_ln1265_13_fu_1396_p3;
wire   [54:0] shl_ln728_39_fu_1404_p3;
wire  signed [69:0] sext_ln1118_52_fu_1392_p1;
wire   [70:0] zext_ln728_33_fu_1412_p1;
wire   [70:0] zext_ln703_33_fu_1416_p1;
wire  signed [31:0] mul_ln1118_38_fu_1426_p0;
wire  signed [34:0] mul_ln1118_38_fu_1426_p1;
wire   [66:0] mul_ln1118_38_fu_1426_p2;
wire   [34:0] select_ln1265_14_fu_1436_p3;
wire   [54:0] shl_ln728_40_fu_1444_p3;
wire  signed [69:0] sext_ln1118_53_fu_1432_p1;
wire   [70:0] zext_ln728_34_fu_1452_p1;
wire   [70:0] zext_ln703_34_fu_1456_p1;
wire   [34:0] select_ln1117_21_fu_1466_p3;
wire  signed [31:0] mul_ln1118_39_fu_1478_p0;
wire  signed [34:0] mul_ln1118_39_fu_1478_p1;
wire  signed [66:0] sext_ln1118_54_fu_1474_p1;
wire   [66:0] mul_ln1118_39_fu_1478_p2;
wire   [34:0] select_ln1265_15_fu_1488_p3;
wire   [54:0] shl_ln728_41_fu_1496_p3;
wire  signed [69:0] sext_ln1118_55_fu_1484_p1;
wire   [70:0] zext_ln728_35_fu_1504_p1;
wire   [70:0] zext_ln703_35_fu_1508_p1;
wire  signed [31:0] mul_ln1118_40_fu_1518_p0;
wire  signed [34:0] mul_ln1118_40_fu_1518_p1;
wire   [66:0] mul_ln1118_40_fu_1518_p2;
wire   [34:0] select_ln1265_16_fu_1528_p3;
wire   [54:0] shl_ln728_42_fu_1536_p3;
wire  signed [69:0] sext_ln1118_56_fu_1524_p1;
wire   [70:0] zext_ln728_36_fu_1544_p1;
wire   [70:0] zext_ln703_36_fu_1548_p1;
wire  signed [34:0] select_ln1117_22_fu_1558_p3;
wire  signed [31:0] mul_ln1118_41_fu_1570_p0;
wire  signed [34:0] mul_ln1118_41_fu_1570_p1;
wire   [66:0] mul_ln1118_41_fu_1570_p2;
wire   [34:0] select_ln1265_17_fu_1580_p3;
wire   [54:0] shl_ln728_43_fu_1588_p3;
wire  signed [69:0] sext_ln1118_58_fu_1576_p1;
wire   [70:0] zext_ln728_37_fu_1596_p1;
wire   [70:0] zext_ln703_37_fu_1600_p1;
wire   [34:0] select_ln1265_18_fu_1618_p3;
wire  signed [31:0] mul_ln1192_fu_1634_p0;
wire  signed [34:0] mul_ln1192_fu_1634_p1;
wire   [54:0] shl_ln728_44_fu_1626_p3;
wire   [54:0] mul_ln1192_fu_1634_p2;
wire   [31:0] trunc_ln1116_4_fu_1646_p1;
wire   [31:0] trunc_ln1116_5_fu_1650_p1;
wire   [70:0] add_ln1192_fu_940_p2;
wire   [31:0] trunc_ln1116_6_fu_1680_p1;
wire   [31:0] trunc_ln1116_7_fu_1684_p1;
wire   [70:0] add_ln1192_32_fu_1000_p2;
wire   [70:0] add_ln1192_33_fu_1052_p2;
wire   [70:0] add_ln1192_34_fu_1092_p2;
wire   [70:0] add_ln1192_35_fu_1144_p2;
wire   [70:0] add_ln1192_36_fu_1184_p2;
wire   [70:0] add_ln1192_37_fu_1236_p2;
wire   [70:0] add_ln1192_38_fu_1276_p2;
wire   [70:0] add_ln1192_39_fu_1328_p2;
wire   [70:0] add_ln1192_40_fu_1368_p2;
wire   [70:0] add_ln1192_41_fu_1420_p2;
wire   [70:0] add_ln1192_42_fu_1460_p2;
wire   [70:0] add_ln1192_43_fu_1512_p2;
wire   [70:0] add_ln1192_44_fu_1552_p2;
wire   [70:0] add_ln1192_45_fu_1604_p2;
wire   [54:0] add_ln1192_46_fu_1640_p2;
wire  signed [31:0] mul_ln1118_42_fu_1908_p0;
wire  signed [66:0] sext_ln1117_1_fu_1902_p1;
wire  signed [34:0] mul_ln1118_42_fu_1908_p1;
wire  signed [66:0] sext_ln1118_59_fu_1905_p1;
wire   [66:0] mul_ln1118_42_fu_1908_p2;
wire   [54:0] shl_ln728_45_fu_1918_p3;
wire  signed [69:0] sext_ln1118_60_fu_1914_p1;
wire   [70:0] zext_ln728_38_fu_1925_p1;
wire   [70:0] zext_ln703_38_fu_1929_p1;
wire   [70:0] add_ln1192_47_fu_1933_p2;
wire  signed [31:0] mul_ln1118_43_fu_1952_p0;
wire  signed [66:0] sext_ln1118_61_fu_1949_p1;
wire  signed [34:0] mul_ln1118_43_fu_1952_p1;
wire   [66:0] mul_ln1118_43_fu_1952_p2;
wire   [54:0] shl_ln728_46_fu_1962_p3;
wire  signed [69:0] sext_ln1118_62_fu_1958_p1;
wire   [70:0] zext_ln728_39_fu_1969_p1;
wire   [70:0] zext_ln703_39_fu_1973_p1;
wire   [70:0] add_ln1192_48_fu_1977_p2;
wire  signed [31:0] mul_ln1118_44_fu_1996_p0;
wire  signed [34:0] mul_ln1118_44_fu_1996_p1;
wire  signed [66:0] sext_ln1118_63_fu_1993_p1;
wire   [66:0] mul_ln1118_44_fu_1996_p2;
wire   [54:0] shl_ln728_47_fu_2006_p3;
wire  signed [69:0] sext_ln1118_64_fu_2002_p1;
wire   [70:0] zext_ln728_40_fu_2013_p1;
wire   [70:0] zext_ln703_40_fu_2017_p1;
wire   [70:0] add_ln1192_49_fu_2021_p2;
wire  signed [31:0] mul_ln1118_45_fu_2037_p0;
wire  signed [34:0] mul_ln1118_45_fu_2037_p1;
wire   [66:0] mul_ln1118_45_fu_2037_p2;
wire   [54:0] shl_ln728_48_fu_2047_p3;
wire  signed [69:0] sext_ln1118_65_fu_2043_p1;
wire   [70:0] zext_ln728_41_fu_2054_p1;
wire   [70:0] zext_ln703_41_fu_2058_p1;
wire   [70:0] add_ln1192_50_fu_2062_p2;
wire  signed [31:0] mul_ln1118_46_fu_2081_p0;
wire  signed [34:0] mul_ln1118_46_fu_2081_p1;
wire  signed [66:0] sext_ln1118_66_fu_2078_p1;
wire   [66:0] mul_ln1118_46_fu_2081_p2;
wire   [54:0] shl_ln728_49_fu_2091_p3;
wire  signed [69:0] sext_ln1118_67_fu_2087_p1;
wire   [70:0] zext_ln728_42_fu_2098_p1;
wire   [70:0] zext_ln703_42_fu_2102_p1;
wire   [70:0] add_ln1192_51_fu_2106_p2;
wire  signed [31:0] mul_ln1118_47_fu_2122_p0;
wire  signed [34:0] mul_ln1118_47_fu_2122_p1;
wire   [66:0] mul_ln1118_47_fu_2122_p2;
wire   [54:0] shl_ln728_50_fu_2132_p3;
wire  signed [69:0] sext_ln1118_68_fu_2128_p1;
wire   [70:0] zext_ln728_43_fu_2139_p1;
wire   [70:0] zext_ln703_43_fu_2143_p1;
wire   [70:0] add_ln1192_52_fu_2147_p2;
wire  signed [31:0] mul_ln1118_48_fu_2166_p0;
wire  signed [34:0] mul_ln1118_48_fu_2166_p1;
wire  signed [66:0] sext_ln1118_69_fu_2163_p1;
wire   [66:0] mul_ln1118_48_fu_2166_p2;
wire   [54:0] shl_ln728_51_fu_2176_p3;
wire  signed [69:0] sext_ln1118_70_fu_2172_p1;
wire   [70:0] zext_ln728_44_fu_2183_p1;
wire   [70:0] zext_ln703_44_fu_2187_p1;
wire   [70:0] add_ln1192_53_fu_2191_p2;
wire  signed [31:0] mul_ln1118_49_fu_2207_p0;
wire  signed [34:0] mul_ln1118_49_fu_2207_p1;
wire   [66:0] mul_ln1118_49_fu_2207_p2;
wire   [54:0] shl_ln728_52_fu_2217_p3;
wire  signed [69:0] sext_ln1118_71_fu_2213_p1;
wire   [70:0] zext_ln728_45_fu_2224_p1;
wire   [70:0] zext_ln703_45_fu_2228_p1;
wire   [70:0] add_ln1192_54_fu_2232_p2;
wire  signed [31:0] mul_ln1118_50_fu_2251_p0;
wire  signed [34:0] mul_ln1118_50_fu_2251_p1;
wire  signed [66:0] sext_ln1118_72_fu_2248_p1;
wire   [66:0] mul_ln1118_50_fu_2251_p2;
wire   [54:0] shl_ln728_53_fu_2261_p3;
wire  signed [69:0] sext_ln1118_73_fu_2257_p1;
wire   [70:0] zext_ln728_46_fu_2268_p1;
wire   [70:0] zext_ln703_46_fu_2272_p1;
wire   [70:0] add_ln1192_55_fu_2276_p2;
wire  signed [31:0] mul_ln1118_51_fu_2292_p0;
wire  signed [34:0] mul_ln1118_51_fu_2292_p1;
wire   [66:0] mul_ln1118_51_fu_2292_p2;
wire   [54:0] shl_ln728_54_fu_2302_p3;
wire  signed [69:0] sext_ln1118_74_fu_2298_p1;
wire   [70:0] zext_ln728_47_fu_2309_p1;
wire   [70:0] zext_ln703_47_fu_2313_p1;
wire   [70:0] add_ln1192_56_fu_2317_p2;
wire  signed [31:0] mul_ln1118_52_fu_2336_p0;
wire  signed [34:0] mul_ln1118_52_fu_2336_p1;
wire  signed [66:0] sext_ln1118_75_fu_2333_p1;
wire   [66:0] mul_ln1118_52_fu_2336_p2;
wire   [54:0] shl_ln728_55_fu_2346_p3;
wire  signed [69:0] sext_ln1118_76_fu_2342_p1;
wire   [70:0] zext_ln728_48_fu_2353_p1;
wire   [70:0] zext_ln703_48_fu_2357_p1;
wire   [70:0] add_ln1192_57_fu_2361_p2;
wire  signed [31:0] mul_ln1118_53_fu_2377_p0;
wire  signed [34:0] mul_ln1118_53_fu_2377_p1;
wire   [66:0] mul_ln1118_53_fu_2377_p2;
wire   [54:0] shl_ln728_56_fu_2387_p3;
wire  signed [69:0] sext_ln1118_77_fu_2383_p1;
wire   [70:0] zext_ln728_49_fu_2394_p1;
wire   [70:0] zext_ln703_49_fu_2398_p1;
wire   [70:0] add_ln1192_58_fu_2402_p2;
wire  signed [31:0] mul_ln1118_54_fu_2421_p0;
wire  signed [34:0] mul_ln1118_54_fu_2421_p1;
wire  signed [66:0] sext_ln1118_78_fu_2418_p1;
wire   [66:0] mul_ln1118_54_fu_2421_p2;
wire   [54:0] shl_ln728_57_fu_2431_p3;
wire  signed [69:0] sext_ln1118_79_fu_2427_p1;
wire   [70:0] zext_ln728_50_fu_2438_p1;
wire   [70:0] zext_ln703_50_fu_2442_p1;
wire   [70:0] add_ln1192_59_fu_2446_p2;
wire  signed [31:0] mul_ln1118_55_fu_2462_p0;
wire  signed [34:0] mul_ln1118_55_fu_2462_p1;
wire   [66:0] mul_ln1118_55_fu_2462_p2;
wire   [54:0] shl_ln728_58_fu_2472_p3;
wire  signed [69:0] sext_ln1118_80_fu_2468_p1;
wire   [70:0] zext_ln728_51_fu_2479_p1;
wire   [70:0] zext_ln703_51_fu_2483_p1;
wire   [70:0] add_ln1192_60_fu_2487_p2;
wire  signed [31:0] mul_ln1118_56_fu_2506_p0;
wire  signed [34:0] mul_ln1118_56_fu_2506_p1;
wire   [66:0] mul_ln1118_56_fu_2506_p2;
wire   [54:0] shl_ln728_59_fu_2516_p3;
wire  signed [69:0] sext_ln1118_82_fu_2512_p1;
wire   [70:0] zext_ln728_52_fu_2523_p1;
wire   [70:0] zext_ln703_52_fu_2527_p1;
wire   [70:0] add_ln1192_61_fu_2531_p2;
wire  signed [31:0] mul_ln1192_8_fu_2560_p0;
wire  signed [34:0] mul_ln1192_8_fu_2560_p1;
wire   [54:0] shl_ln728_60_fu_2553_p3;
wire   [54:0] mul_ln1192_8_fu_2560_p2;
wire   [54:0] add_ln1192_62_fu_2566_p2;
wire   [34:0] trunc_ln708_15_fu_2572_p4;
wire   [34:0] trunc_ln708_s_fu_1939_p4;
wire   [34:0] trunc_ln708_5_fu_1983_p4;
wire   [34:0] trunc_ln708_6_fu_2027_p4;
wire   [34:0] trunc_ln708_7_fu_2068_p4;
wire   [34:0] trunc_ln708_8_fu_2112_p4;
wire   [34:0] trunc_ln708_9_fu_2153_p4;
wire   [34:0] trunc_ln708_1_fu_2197_p4;
wire   [34:0] trunc_ln708_2_fu_2238_p4;
wire   [34:0] trunc_ln708_3_fu_2282_p4;
wire   [34:0] trunc_ln708_4_fu_2323_p4;
wire   [34:0] trunc_ln708_10_fu_2367_p4;
wire   [34:0] trunc_ln708_11_fu_2408_p4;
wire   [34:0] trunc_ln708_12_fu_2452_p4;
wire   [34:0] trunc_ln708_13_fu_2493_p4;
wire   [34:0] trunc_ln708_14_fu_2537_p4;
wire   [34:0] select_ln338_fu_2594_p3;
wire   [34:0] select_ln338_6_fu_2600_p3;
wire   [34:0] select_ln338_7_fu_2606_p3;
wire   [34:0] select_ln338_8_fu_2612_p3;
wire   [34:0] select_ln338_9_fu_2618_p3;
wire   [34:0] select_ln338_10_fu_2624_p3;
wire   [34:0] select_ln338_11_fu_2630_p3;
wire   [34:0] select_ln338_12_fu_2636_p3;
wire   [34:0] select_ln338_13_fu_2642_p3;
wire   [34:0] select_ln338_14_fu_2648_p3;
wire   [34:0] select_ln338_15_fu_2654_p3;
wire   [34:0] select_ln338_16_fu_2660_p3;
wire   [34:0] select_ln338_17_fu_2666_p3;
wire   [34:0] select_ln338_18_fu_2672_p3;
wire   [34:0] select_ln338_19_fu_2678_p3;
wire   [34:0] select_ln338_20_fu_2684_p3;
wire   [34:0] select_ln338_21_fu_2690_p3;
wire   [34:0] select_ln338_22_fu_2696_p3;
wire   [34:0] select_ln338_23_fu_2702_p3;
wire   [34:0] select_ln338_24_fu_2708_p3;
wire   [34:0] select_ln338_25_fu_2714_p3;
wire   [34:0] select_ln338_26_fu_2720_p3;
wire   [34:0] select_ln338_27_fu_2726_p3;
wire   [34:0] select_ln338_28_fu_2732_p3;
wire   [34:0] select_ln338_29_fu_2738_p3;
wire   [34:0] select_ln338_30_fu_2744_p3;
wire   [34:0] select_ln338_31_fu_2750_p3;
wire   [34:0] select_ln338_32_fu_2756_p3;
wire   [34:0] select_ln338_33_fu_2762_p3;
wire   [34:0] select_ln338_34_fu_2768_p3;
wire   [34:0] select_ln708_fu_2582_p3;
wire   [34:0] select_ln708_2_fu_2588_p3;
reg    ap_ce_reg;
reg   [34:0] ap_return_0_int_reg;
reg   [34:0] ap_return_1_int_reg;
reg   [34:0] ap_return_2_int_reg;
reg   [34:0] ap_return_3_int_reg;
reg   [34:0] ap_return_4_int_reg;
reg   [34:0] ap_return_5_int_reg;
reg   [34:0] ap_return_6_int_reg;
reg   [34:0] ap_return_7_int_reg;
reg   [34:0] ap_return_8_int_reg;
reg   [34:0] ap_return_9_int_reg;
reg   [34:0] ap_return_10_int_reg;
reg   [34:0] ap_return_11_int_reg;
reg   [34:0] ap_return_12_int_reg;
reg   [34:0] ap_return_13_int_reg;
reg   [34:0] ap_return_14_int_reg;
reg   [34:0] ap_return_15_int_reg;
reg   [34:0] ap_return_16_int_reg;
reg   [34:0] ap_return_17_int_reg;
reg   [34:0] ap_return_18_int_reg;
reg   [34:0] ap_return_19_int_reg;
reg   [34:0] ap_return_20_int_reg;
reg   [34:0] ap_return_21_int_reg;
reg   [34:0] ap_return_22_int_reg;
reg   [34:0] ap_return_23_int_reg;
reg   [34:0] ap_return_24_int_reg;
reg   [34:0] ap_return_25_int_reg;
reg   [34:0] ap_return_26_int_reg;
reg   [34:0] ap_return_27_int_reg;
reg   [34:0] ap_return_28_int_reg;
reg   [34:0] ap_return_29_int_reg;
reg   [34:0] ap_return_30_int_reg;
reg   [34:0] ap_return_31_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= select_ln338_fu_2594_p3;
        ap_return_10_int_reg <= select_ln338_15_fu_2654_p3;
        ap_return_11_int_reg <= select_ln338_16_fu_2660_p3;
        ap_return_12_int_reg <= select_ln338_17_fu_2666_p3;
        ap_return_13_int_reg <= select_ln338_18_fu_2672_p3;
        ap_return_14_int_reg <= select_ln338_19_fu_2678_p3;
        ap_return_15_int_reg <= select_ln338_20_fu_2684_p3;
        ap_return_16_int_reg <= select_ln338_21_fu_2690_p3;
        ap_return_17_int_reg <= select_ln338_22_fu_2696_p3;
        ap_return_18_int_reg <= select_ln338_23_fu_2702_p3;
        ap_return_19_int_reg <= select_ln338_24_fu_2708_p3;
        ap_return_1_int_reg <= select_ln338_6_fu_2600_p3;
        ap_return_20_int_reg <= select_ln338_25_fu_2714_p3;
        ap_return_21_int_reg <= select_ln338_26_fu_2720_p3;
        ap_return_22_int_reg <= select_ln338_27_fu_2726_p3;
        ap_return_23_int_reg <= select_ln338_28_fu_2732_p3;
        ap_return_24_int_reg <= select_ln338_29_fu_2738_p3;
        ap_return_25_int_reg <= select_ln338_30_fu_2744_p3;
        ap_return_26_int_reg <= select_ln338_31_fu_2750_p3;
        ap_return_27_int_reg <= select_ln338_32_fu_2756_p3;
        ap_return_28_int_reg <= select_ln338_33_fu_2762_p3;
        ap_return_29_int_reg <= select_ln338_34_fu_2768_p3;
        ap_return_2_int_reg <= select_ln338_7_fu_2606_p3;
        ap_return_30_int_reg <= select_ln708_fu_2582_p3;
        ap_return_31_int_reg <= select_ln708_2_fu_2588_p3;
        ap_return_3_int_reg <= select_ln338_8_fu_2612_p3;
        ap_return_4_int_reg <= select_ln338_9_fu_2618_p3;
        ap_return_5_int_reg <= select_ln338_10_fu_2624_p3;
        ap_return_6_int_reg <= select_ln338_11_fu_2630_p3;
        ap_return_7_int_reg <= select_ln338_12_fu_2636_p3;
        ap_return_8_int_reg <= select_ln338_13_fu_2642_p3;
        ap_return_9_int_reg <= select_ln338_14_fu_2648_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_0_0_V_read_6_reg_3157 <= res_0_0_V_read_4;
        res_0_1_V_read_6_reg_3152 <= res_0_1_V_read_4;
        res_10_0_V_read_4_reg_3057 <= res_10_0_V_read_2;
        res_10_1_V_read_4_reg_3052 <= res_10_1_V_read_2;
        res_11_0_V_read_3_reg_3047 <= res_11_0_V_read_2;
        res_11_1_V_read_4_reg_3042 <= res_11_1_V_read_2;
        res_12_0_V_read_4_reg_3037 <= res_12_0_V_read_2;
        res_12_1_V_read_4_reg_3032 <= res_12_1_V_read_2;
        res_13_0_V_read_4_reg_3027 <= res_13_0_V_read_2;
        res_13_1_V_read_3_reg_3022 <= res_13_1_V_read_2;
        res_14_0_V_read_4_reg_3017 <= res_14_0_V_read_2;
        res_14_1_V_read_4_reg_3012 <= res_14_1_V_read_2;
        res_15_0_V_read_4_reg_3007 <= res_15_0_V_read_2;
        res_15_1_V_read_4_reg_3002 <= res_15_1_V_read_2;
        res_1_0_V_read_5_reg_3147 <= res_1_0_V_read_4;
        res_1_1_V_read_5_reg_3142 <= res_1_1_V_read_4;
        res_2_0_V_read_6_reg_3137 <= res_2_0_V_read_4;
        res_2_1_V_read_6_reg_3132 <= res_2_1_V_read_4;
        res_3_0_V_read_6_reg_3127 <= res_3_0_V_read_4;
        res_3_1_V_read_5_reg_3122 <= res_3_1_V_read_4;
        res_4_0_V_read_4_reg_3117 <= res_4_0_V_read_2;
        res_4_1_V_read_4_reg_3112 <= res_4_1_V_read_2;
        res_5_0_V_read_4_reg_3107 <= res_5_0_V_read_2;
        res_5_1_V_read_4_reg_3102 <= res_5_1_V_read_2;
        res_6_0_V_read_3_reg_3097 <= res_6_0_V_read_2;
        res_6_1_V_read_4_reg_3092 <= res_6_1_V_read_2;
        res_7_0_V_read_4_reg_3087 <= res_7_0_V_read_2;
        res_7_1_V_read_4_reg_3082 <= res_7_1_V_read_2;
        res_8_0_V_read_4_reg_3077 <= res_8_0_V_read_2;
        res_8_1_V_read_3_reg_3072 <= res_8_1_V_read_2;
        res_9_0_V_read_4_reg_3067 <= res_9_0_V_read_2;
        res_9_1_V_read_4_reg_3062 <= res_9_1_V_read_2;
        res_V_offset_read_reg_2966 <= res_V_offset;
        select_ln1116_17_reg_3162 <= select_ln1116_17_fu_1654_p3;
        select_ln1116_18_reg_3177 <= select_ln1116_18_fu_1688_p3;
        select_ln1117_23_reg_3167 <= select_ln1117_23_fu_1662_p3;
        select_ln1117_24_reg_3188 <= select_ln1117_24_fu_1706_p3;
        select_ln1117_25_reg_3203 <= select_ln1117_25_fu_1734_p3;
        select_ln1117_26_reg_3218 <= select_ln1117_26_fu_1762_p3;
        select_ln1117_27_reg_3233 <= select_ln1117_27_fu_1790_p3;
        select_ln1117_28_reg_3248 <= select_ln1117_28_fu_1818_p3;
        select_ln1117_29_reg_3263 <= select_ln1117_29_fu_1846_p3;
        select_ln1117_30_reg_3278 <= select_ln1117_30_fu_1874_p3;
        tmp_27_reg_3193 <= {{add_ln1192_33_fu_1052_p2[54:20]}};
        tmp_28_reg_3198 <= {{add_ln1192_34_fu_1092_p2[54:20]}};
        tmp_29_reg_3208 <= {{add_ln1192_35_fu_1144_p2[54:20]}};
        tmp_30_reg_3213 <= {{add_ln1192_36_fu_1184_p2[54:20]}};
        tmp_31_reg_3223 <= {{add_ln1192_37_fu_1236_p2[54:20]}};
        tmp_32_reg_3228 <= {{add_ln1192_38_fu_1276_p2[54:20]}};
        tmp_33_reg_3238 <= {{add_ln1192_39_fu_1328_p2[54:20]}};
        tmp_34_reg_3243 <= {{add_ln1192_40_fu_1368_p2[54:20]}};
        tmp_35_reg_3253 <= {{add_ln1192_41_fu_1420_p2[54:20]}};
        tmp_36_reg_3258 <= {{add_ln1192_42_fu_1460_p2[54:20]}};
        tmp_37_reg_3268 <= {{add_ln1192_43_fu_1512_p2[54:20]}};
        tmp_38_reg_3273 <= {{add_ln1192_44_fu_1552_p2[54:20]}};
        tmp_39_reg_3284 <= {{add_ln1192_45_fu_1604_p2[54:20]}};
        tmp_40_reg_3289 <= {{add_ln1192_46_fu_1640_p2[54:20]}};
        tmp_reg_3172 <= {{add_ln1192_fu_940_p2[54:20]}};
        tmp_s_reg_3183 <= {{add_ln1192_32_fu_1000_p2[54:20]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = select_ln338_fu_2594_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = select_ln338_6_fu_2600_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_10 = ap_return_10_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_10 = select_ln338_15_fu_2654_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_11 = ap_return_11_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_11 = select_ln338_16_fu_2660_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_12 = ap_return_12_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_12 = select_ln338_17_fu_2666_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_13 = ap_return_13_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_13 = select_ln338_18_fu_2672_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_14 = ap_return_14_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_14 = select_ln338_19_fu_2678_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_15 = ap_return_15_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_15 = select_ln338_20_fu_2684_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_16 = ap_return_16_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_16 = select_ln338_21_fu_2690_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_17 = ap_return_17_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_17 = select_ln338_22_fu_2696_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_18 = ap_return_18_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_18 = select_ln338_23_fu_2702_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_19 = ap_return_19_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_19 = select_ln338_24_fu_2708_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = select_ln338_7_fu_2606_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_20 = ap_return_20_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_20 = select_ln338_25_fu_2714_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_21 = ap_return_21_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_21 = select_ln338_26_fu_2720_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_22 = ap_return_22_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_22 = select_ln338_27_fu_2726_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_23 = ap_return_23_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_23 = select_ln338_28_fu_2732_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_24 = ap_return_24_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_24 = select_ln338_29_fu_2738_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_25 = ap_return_25_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_25 = select_ln338_30_fu_2744_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_26 = ap_return_26_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_26 = select_ln338_31_fu_2750_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_27 = ap_return_27_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_27 = select_ln338_32_fu_2756_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_28 = ap_return_28_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_28 = select_ln338_33_fu_2762_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_29 = ap_return_29_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_29 = select_ln338_34_fu_2768_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = select_ln338_8_fu_2612_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_30 = ap_return_30_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_30 = select_ln708_fu_2582_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_31 = ap_return_31_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_31 = select_ln708_2_fu_2588_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = select_ln338_9_fu_2618_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = select_ln338_10_fu_2624_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = select_ln338_11_fu_2630_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = select_ln338_12_fu_2636_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_8 = ap_return_8_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_8 = select_ln338_13_fu_2642_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_9 = ap_return_9_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_9 = select_ln338_14_fu_2648_p3;
    end
end

assign add_ln1192_32_fu_1000_p2 = (zext_ln728_24_fu_992_p1 + zext_ln703_24_fu_996_p1);

assign add_ln1192_33_fu_1052_p2 = (zext_ln728_25_fu_1044_p1 + zext_ln703_25_fu_1048_p1);

assign add_ln1192_34_fu_1092_p2 = (zext_ln728_26_fu_1084_p1 + zext_ln703_26_fu_1088_p1);

assign add_ln1192_35_fu_1144_p2 = (zext_ln728_27_fu_1136_p1 + zext_ln703_27_fu_1140_p1);

assign add_ln1192_36_fu_1184_p2 = (zext_ln728_28_fu_1176_p1 + zext_ln703_28_fu_1180_p1);

assign add_ln1192_37_fu_1236_p2 = (zext_ln728_29_fu_1228_p1 + zext_ln703_29_fu_1232_p1);

assign add_ln1192_38_fu_1276_p2 = (zext_ln728_30_fu_1268_p1 + zext_ln703_30_fu_1272_p1);

assign add_ln1192_39_fu_1328_p2 = (zext_ln728_31_fu_1320_p1 + zext_ln703_31_fu_1324_p1);

assign add_ln1192_40_fu_1368_p2 = (zext_ln728_32_fu_1360_p1 + zext_ln703_32_fu_1364_p1);

assign add_ln1192_41_fu_1420_p2 = (zext_ln728_33_fu_1412_p1 + zext_ln703_33_fu_1416_p1);

assign add_ln1192_42_fu_1460_p2 = (zext_ln728_34_fu_1452_p1 + zext_ln703_34_fu_1456_p1);

assign add_ln1192_43_fu_1512_p2 = (zext_ln728_35_fu_1504_p1 + zext_ln703_35_fu_1508_p1);

assign add_ln1192_44_fu_1552_p2 = (zext_ln728_36_fu_1544_p1 + zext_ln703_36_fu_1548_p1);

assign add_ln1192_45_fu_1604_p2 = (zext_ln728_37_fu_1596_p1 + zext_ln703_37_fu_1600_p1);

assign add_ln1192_46_fu_1640_p2 = (shl_ln728_44_fu_1626_p3 + mul_ln1192_fu_1634_p2);

assign add_ln1192_47_fu_1933_p2 = (zext_ln728_38_fu_1925_p1 + zext_ln703_38_fu_1929_p1);

assign add_ln1192_48_fu_1977_p2 = (zext_ln728_39_fu_1969_p1 + zext_ln703_39_fu_1973_p1);

assign add_ln1192_49_fu_2021_p2 = (zext_ln728_40_fu_2013_p1 + zext_ln703_40_fu_2017_p1);

assign add_ln1192_50_fu_2062_p2 = (zext_ln728_41_fu_2054_p1 + zext_ln703_41_fu_2058_p1);

assign add_ln1192_51_fu_2106_p2 = (zext_ln728_42_fu_2098_p1 + zext_ln703_42_fu_2102_p1);

assign add_ln1192_52_fu_2147_p2 = (zext_ln728_43_fu_2139_p1 + zext_ln703_43_fu_2143_p1);

assign add_ln1192_53_fu_2191_p2 = (zext_ln728_44_fu_2183_p1 + zext_ln703_44_fu_2187_p1);

assign add_ln1192_54_fu_2232_p2 = (zext_ln728_45_fu_2224_p1 + zext_ln703_45_fu_2228_p1);

assign add_ln1192_55_fu_2276_p2 = (zext_ln728_46_fu_2268_p1 + zext_ln703_46_fu_2272_p1);

assign add_ln1192_56_fu_2317_p2 = (zext_ln728_47_fu_2309_p1 + zext_ln703_47_fu_2313_p1);

assign add_ln1192_57_fu_2361_p2 = (zext_ln728_48_fu_2353_p1 + zext_ln703_48_fu_2357_p1);

assign add_ln1192_58_fu_2402_p2 = (zext_ln728_49_fu_2394_p1 + zext_ln703_49_fu_2398_p1);

assign add_ln1192_59_fu_2446_p2 = (zext_ln728_50_fu_2438_p1 + zext_ln703_50_fu_2442_p1);

assign add_ln1192_60_fu_2487_p2 = (zext_ln728_51_fu_2479_p1 + zext_ln703_51_fu_2483_p1);

assign add_ln1192_61_fu_2531_p2 = (zext_ln728_52_fu_2523_p1 + zext_ln703_52_fu_2527_p1);

assign add_ln1192_62_fu_2566_p2 = (shl_ln728_60_fu_2553_p3 + mul_ln1192_8_fu_2560_p2);

assign add_ln1192_fu_940_p2 = (zext_ln728_fu_932_p1 + zext_ln703_fu_936_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign mul_ln1118_28_fu_966_p0 = sext_ln1118_37_fu_962_p1;

assign mul_ln1118_28_fu_966_p1 = sext_ln1118_fu_902_p1;

assign mul_ln1118_28_fu_966_p2 = ($signed(mul_ln1118_28_fu_966_p0) * $signed(mul_ln1118_28_fu_966_p1));

assign mul_ln1118_29_fu_1018_p0 = sext_ln1117_fu_890_p1;

assign mul_ln1118_29_fu_1018_p1 = sext_ln1118_39_fu_1014_p1;

assign mul_ln1118_29_fu_1018_p2 = ($signed(mul_ln1118_29_fu_1018_p0) * $signed(mul_ln1118_29_fu_1018_p1));

assign mul_ln1118_30_fu_1058_p0 = sext_ln1118_37_fu_962_p1;

assign mul_ln1118_30_fu_1058_p1 = sext_ln1118_39_fu_1014_p1;

assign mul_ln1118_30_fu_1058_p2 = ($signed(mul_ln1118_30_fu_1058_p0) * $signed(mul_ln1118_30_fu_1058_p1));

assign mul_ln1118_31_fu_1110_p0 = sext_ln1117_fu_890_p1;

assign mul_ln1118_31_fu_1110_p1 = sext_ln1118_42_fu_1106_p1;

assign mul_ln1118_31_fu_1110_p2 = ($signed(mul_ln1118_31_fu_1110_p0) * $signed(mul_ln1118_31_fu_1110_p1));

assign mul_ln1118_32_fu_1150_p0 = sext_ln1118_37_fu_962_p1;

assign mul_ln1118_32_fu_1150_p1 = sext_ln1118_42_fu_1106_p1;

assign mul_ln1118_32_fu_1150_p2 = ($signed(mul_ln1118_32_fu_1150_p0) * $signed(mul_ln1118_32_fu_1150_p1));

assign mul_ln1118_33_fu_1202_p0 = sext_ln1117_fu_890_p1;

assign mul_ln1118_33_fu_1202_p1 = sext_ln1118_45_fu_1198_p1;

assign mul_ln1118_33_fu_1202_p2 = ($signed(mul_ln1118_33_fu_1202_p0) * $signed(mul_ln1118_33_fu_1202_p1));

assign mul_ln1118_34_fu_1242_p0 = sext_ln1118_37_fu_962_p1;

assign mul_ln1118_34_fu_1242_p1 = sext_ln1118_45_fu_1198_p1;

assign mul_ln1118_34_fu_1242_p2 = ($signed(mul_ln1118_34_fu_1242_p0) * $signed(mul_ln1118_34_fu_1242_p1));

assign mul_ln1118_35_fu_1294_p0 = sext_ln1117_fu_890_p1;

assign mul_ln1118_35_fu_1294_p1 = sext_ln1118_48_fu_1290_p1;

assign mul_ln1118_35_fu_1294_p2 = ($signed(mul_ln1118_35_fu_1294_p0) * $signed(mul_ln1118_35_fu_1294_p1));

assign mul_ln1118_36_fu_1334_p0 = sext_ln1118_37_fu_962_p1;

assign mul_ln1118_36_fu_1334_p1 = sext_ln1118_48_fu_1290_p1;

assign mul_ln1118_36_fu_1334_p2 = ($signed(mul_ln1118_36_fu_1334_p0) * $signed(mul_ln1118_36_fu_1334_p1));

assign mul_ln1118_37_fu_1386_p0 = sext_ln1117_fu_890_p1;

assign mul_ln1118_37_fu_1386_p1 = sext_ln1118_51_fu_1382_p1;

assign mul_ln1118_37_fu_1386_p2 = ($signed(mul_ln1118_37_fu_1386_p0) * $signed(mul_ln1118_37_fu_1386_p1));

assign mul_ln1118_38_fu_1426_p0 = sext_ln1118_37_fu_962_p1;

assign mul_ln1118_38_fu_1426_p1 = sext_ln1118_51_fu_1382_p1;

assign mul_ln1118_38_fu_1426_p2 = ($signed(mul_ln1118_38_fu_1426_p0) * $signed(mul_ln1118_38_fu_1426_p1));

assign mul_ln1118_39_fu_1478_p0 = sext_ln1117_fu_890_p1;

assign mul_ln1118_39_fu_1478_p1 = sext_ln1118_54_fu_1474_p1;

assign mul_ln1118_39_fu_1478_p2 = ($signed(mul_ln1118_39_fu_1478_p0) * $signed(mul_ln1118_39_fu_1478_p1));

assign mul_ln1118_40_fu_1518_p0 = sext_ln1118_37_fu_962_p1;

assign mul_ln1118_40_fu_1518_p1 = sext_ln1118_54_fu_1474_p1;

assign mul_ln1118_40_fu_1518_p2 = ($signed(mul_ln1118_40_fu_1518_p0) * $signed(mul_ln1118_40_fu_1518_p1));

assign mul_ln1118_41_fu_1570_p0 = sext_ln1117_fu_890_p1;

assign mul_ln1118_41_fu_1570_p1 = select_ln1117_22_fu_1558_p3;

assign mul_ln1118_41_fu_1570_p2 = ($signed(mul_ln1118_41_fu_1570_p0) * $signed(mul_ln1118_41_fu_1570_p1));

assign mul_ln1118_42_fu_1908_p0 = sext_ln1117_1_fu_1902_p1;

assign mul_ln1118_42_fu_1908_p1 = sext_ln1118_59_fu_1905_p1;

assign mul_ln1118_42_fu_1908_p2 = ($signed(mul_ln1118_42_fu_1908_p0) * $signed(mul_ln1118_42_fu_1908_p1));

assign mul_ln1118_43_fu_1952_p0 = sext_ln1118_61_fu_1949_p1;

assign mul_ln1118_43_fu_1952_p1 = sext_ln1118_59_fu_1905_p1;

assign mul_ln1118_43_fu_1952_p2 = ($signed(mul_ln1118_43_fu_1952_p0) * $signed(mul_ln1118_43_fu_1952_p1));

assign mul_ln1118_44_fu_1996_p0 = sext_ln1117_1_fu_1902_p1;

assign mul_ln1118_44_fu_1996_p1 = sext_ln1118_63_fu_1993_p1;

assign mul_ln1118_44_fu_1996_p2 = ($signed(mul_ln1118_44_fu_1996_p0) * $signed(mul_ln1118_44_fu_1996_p1));

assign mul_ln1118_45_fu_2037_p0 = sext_ln1118_61_fu_1949_p1;

assign mul_ln1118_45_fu_2037_p1 = sext_ln1118_63_fu_1993_p1;

assign mul_ln1118_45_fu_2037_p2 = ($signed(mul_ln1118_45_fu_2037_p0) * $signed(mul_ln1118_45_fu_2037_p1));

assign mul_ln1118_46_fu_2081_p0 = sext_ln1117_1_fu_1902_p1;

assign mul_ln1118_46_fu_2081_p1 = sext_ln1118_66_fu_2078_p1;

assign mul_ln1118_46_fu_2081_p2 = ($signed(mul_ln1118_46_fu_2081_p0) * $signed(mul_ln1118_46_fu_2081_p1));

assign mul_ln1118_47_fu_2122_p0 = sext_ln1118_61_fu_1949_p1;

assign mul_ln1118_47_fu_2122_p1 = sext_ln1118_66_fu_2078_p1;

assign mul_ln1118_47_fu_2122_p2 = ($signed(mul_ln1118_47_fu_2122_p0) * $signed(mul_ln1118_47_fu_2122_p1));

assign mul_ln1118_48_fu_2166_p0 = sext_ln1117_1_fu_1902_p1;

assign mul_ln1118_48_fu_2166_p1 = sext_ln1118_69_fu_2163_p1;

assign mul_ln1118_48_fu_2166_p2 = ($signed(mul_ln1118_48_fu_2166_p0) * $signed(mul_ln1118_48_fu_2166_p1));

assign mul_ln1118_49_fu_2207_p0 = sext_ln1118_61_fu_1949_p1;

assign mul_ln1118_49_fu_2207_p1 = sext_ln1118_69_fu_2163_p1;

assign mul_ln1118_49_fu_2207_p2 = ($signed(mul_ln1118_49_fu_2207_p0) * $signed(mul_ln1118_49_fu_2207_p1));

assign mul_ln1118_50_fu_2251_p0 = sext_ln1117_1_fu_1902_p1;

assign mul_ln1118_50_fu_2251_p1 = sext_ln1118_72_fu_2248_p1;

assign mul_ln1118_50_fu_2251_p2 = ($signed(mul_ln1118_50_fu_2251_p0) * $signed(mul_ln1118_50_fu_2251_p1));

assign mul_ln1118_51_fu_2292_p0 = sext_ln1118_61_fu_1949_p1;

assign mul_ln1118_51_fu_2292_p1 = sext_ln1118_72_fu_2248_p1;

assign mul_ln1118_51_fu_2292_p2 = ($signed(mul_ln1118_51_fu_2292_p0) * $signed(mul_ln1118_51_fu_2292_p1));

assign mul_ln1118_52_fu_2336_p0 = sext_ln1117_1_fu_1902_p1;

assign mul_ln1118_52_fu_2336_p1 = sext_ln1118_75_fu_2333_p1;

assign mul_ln1118_52_fu_2336_p2 = ($signed(mul_ln1118_52_fu_2336_p0) * $signed(mul_ln1118_52_fu_2336_p1));

assign mul_ln1118_53_fu_2377_p0 = sext_ln1118_61_fu_1949_p1;

assign mul_ln1118_53_fu_2377_p1 = sext_ln1118_75_fu_2333_p1;

assign mul_ln1118_53_fu_2377_p2 = ($signed(mul_ln1118_53_fu_2377_p0) * $signed(mul_ln1118_53_fu_2377_p1));

assign mul_ln1118_54_fu_2421_p0 = sext_ln1117_1_fu_1902_p1;

assign mul_ln1118_54_fu_2421_p1 = sext_ln1118_78_fu_2418_p1;

assign mul_ln1118_54_fu_2421_p2 = ($signed(mul_ln1118_54_fu_2421_p0) * $signed(mul_ln1118_54_fu_2421_p1));

assign mul_ln1118_55_fu_2462_p0 = sext_ln1118_61_fu_1949_p1;

assign mul_ln1118_55_fu_2462_p1 = sext_ln1118_78_fu_2418_p1;

assign mul_ln1118_55_fu_2462_p2 = ($signed(mul_ln1118_55_fu_2462_p0) * $signed(mul_ln1118_55_fu_2462_p1));

assign mul_ln1118_56_fu_2506_p0 = sext_ln1117_1_fu_1902_p1;

assign mul_ln1118_56_fu_2506_p1 = select_ln1117_30_reg_3278;

assign mul_ln1118_56_fu_2506_p2 = ($signed(mul_ln1118_56_fu_2506_p0) * $signed(mul_ln1118_56_fu_2506_p1));

assign mul_ln1118_fu_906_p0 = sext_ln1117_fu_890_p1;

assign mul_ln1118_fu_906_p1 = sext_ln1118_fu_902_p1;

assign mul_ln1118_fu_906_p2 = ($signed(mul_ln1118_fu_906_p0) * $signed(mul_ln1118_fu_906_p1));

assign mul_ln1192_8_fu_2560_p0 = select_ln1116_18_reg_3177;

assign mul_ln1192_8_fu_2560_p1 = select_ln1117_30_reg_3278;

assign mul_ln1192_8_fu_2560_p2 = ($signed(mul_ln1192_8_fu_2560_p0) * $signed(mul_ln1192_8_fu_2560_p1));

assign mul_ln1192_fu_1634_p0 = select_ln1116_16_fu_954_p3;

assign mul_ln1192_fu_1634_p1 = select_ln1117_22_fu_1558_p3;

assign mul_ln1192_fu_1634_p2 = ($signed(mul_ln1192_fu_1634_p0) * $signed(mul_ln1192_fu_1634_p1));

assign select_ln1116_16_fu_954_p3 = ((a_V_offset[0:0] === 1'b1) ? trunc_ln1116_2_fu_946_p1 : trunc_ln1116_3_fu_950_p1);

assign select_ln1116_17_fu_1654_p3 = ((a_V_offset[0:0] === 1'b1) ? trunc_ln1116_4_fu_1646_p1 : trunc_ln1116_5_fu_1650_p1);

assign select_ln1116_18_fu_1688_p3 = ((a_V_offset[0:0] === 1'b1) ? trunc_ln1116_6_fu_1680_p1 : trunc_ln1116_7_fu_1684_p1);

assign select_ln1116_fu_882_p3 = ((a_V_offset[0:0] === 1'b1) ? trunc_ln1116_fu_874_p1 : trunc_ln1116_1_fu_878_p1);

assign select_ln1117_16_fu_1006_p3 = ((b_V_offset[0:0] === 1'b1) ? b_2_1_V_read : b_2_0_V_read);

assign select_ln1117_17_fu_1098_p3 = ((b_V_offset[0:0] === 1'b1) ? b_4_1_V_read : b_4_0_V_read);

assign select_ln1117_18_fu_1190_p3 = ((b_V_offset[0:0] === 1'b1) ? b_6_1_V_read : b_6_0_V_read);

assign select_ln1117_19_fu_1282_p3 = ((b_V_offset[0:0] === 1'b1) ? b_8_1_V_read : b_8_0_V_read);

assign select_ln1117_20_fu_1374_p3 = ((b_V_offset[0:0] === 1'b1) ? b_10_1_V_read : b_10_0_V_read);

assign select_ln1117_21_fu_1466_p3 = ((b_V_offset[0:0] === 1'b1) ? b_12_1_V_read : b_12_0_V_read);

assign select_ln1117_22_fu_1558_p3 = ((b_V_offset[0:0] === 1'b1) ? b_14_1_V_read : b_14_0_V_read);

assign select_ln1117_23_fu_1662_p3 = ((b_V_offset[0:0] === 1'b1) ? b_1_1_V_read : b_1_0_V_read);

assign select_ln1117_24_fu_1706_p3 = ((b_V_offset[0:0] === 1'b1) ? b_3_1_V_read : b_3_0_V_read);

assign select_ln1117_25_fu_1734_p3 = ((b_V_offset[0:0] === 1'b1) ? b_5_1_V_read : b_5_0_V_read);

assign select_ln1117_26_fu_1762_p3 = ((b_V_offset[0:0] === 1'b1) ? b_7_1_V_read : b_7_0_V_read);

assign select_ln1117_27_fu_1790_p3 = ((b_V_offset[0:0] === 1'b1) ? b_9_1_V_read : b_9_0_V_read);

assign select_ln1117_28_fu_1818_p3 = ((b_V_offset[0:0] === 1'b1) ? b_11_1_V_read : b_11_0_V_read);

assign select_ln1117_29_fu_1846_p3 = ((b_V_offset[0:0] === 1'b1) ? b_13_1_V_read : b_13_0_V_read);

assign select_ln1117_30_fu_1874_p3 = ((b_V_offset[0:0] === 1'b1) ? b_15_1_V_read : b_15_0_V_read);

assign select_ln1117_fu_894_p3 = ((b_V_offset[0:0] === 1'b1) ? b_0_1_V_read : b_0_0_V_read);

assign select_ln1265_10_fu_1252_p3 = ((res_V_offset[0:0] === 1'b1) ? res_7_1_V_read : res_7_0_V_read);

assign select_ln1265_11_fu_1304_p3 = ((res_V_offset[0:0] === 1'b1) ? res_8_1_V_read : res_8_0_V_read);

assign select_ln1265_12_fu_1344_p3 = ((res_V_offset[0:0] === 1'b1) ? res_9_1_V_read : res_9_0_V_read);

assign select_ln1265_13_fu_1396_p3 = ((res_V_offset[0:0] === 1'b1) ? res_10_1_V_read : res_10_0_V_read);

assign select_ln1265_14_fu_1436_p3 = ((res_V_offset[0:0] === 1'b1) ? res_11_1_V_read : res_11_0_V_read);

assign select_ln1265_15_fu_1488_p3 = ((res_V_offset[0:0] === 1'b1) ? res_12_1_V_read : res_12_0_V_read);

assign select_ln1265_16_fu_1528_p3 = ((res_V_offset[0:0] === 1'b1) ? res_13_1_V_read : res_13_0_V_read);

assign select_ln1265_17_fu_1580_p3 = ((res_V_offset[0:0] === 1'b1) ? res_14_1_V_read : res_14_0_V_read);

assign select_ln1265_18_fu_1618_p3 = ((res_V_offset[0:0] === 1'b1) ? res_15_1_V_read : res_15_0_V_read);

assign select_ln1265_4_fu_976_p3 = ((res_V_offset[0:0] === 1'b1) ? res_1_1_V_read : res_1_0_V_read);

assign select_ln1265_5_fu_1028_p3 = ((res_V_offset[0:0] === 1'b1) ? res_2_1_V_read : res_2_0_V_read);

assign select_ln1265_6_fu_1068_p3 = ((res_V_offset[0:0] === 1'b1) ? res_3_1_V_read : res_3_0_V_read);

assign select_ln1265_7_fu_1120_p3 = ((res_V_offset[0:0] === 1'b1) ? res_4_1_V_read : res_4_0_V_read);

assign select_ln1265_8_fu_1160_p3 = ((res_V_offset[0:0] === 1'b1) ? res_5_1_V_read : res_5_0_V_read);

assign select_ln1265_9_fu_1212_p3 = ((res_V_offset[0:0] === 1'b1) ? res_6_1_V_read : res_6_0_V_read);

assign select_ln1265_fu_916_p3 = ((res_V_offset[0:0] === 1'b1) ? res_0_1_V_read : res_0_0_V_read);

assign select_ln338_10_fu_2624_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_6_fu_2027_p4 : res_2_1_V_read_6_reg_3132);

assign select_ln338_11_fu_2630_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_3_0_V_read_6_reg_3127 : trunc_ln708_7_fu_2068_p4);

assign select_ln338_12_fu_2636_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_7_fu_2068_p4 : res_3_1_V_read_5_reg_3122);

assign select_ln338_13_fu_2642_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_4_0_V_read_4_reg_3117 : trunc_ln708_8_fu_2112_p4);

assign select_ln338_14_fu_2648_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_8_fu_2112_p4 : res_4_1_V_read_4_reg_3112);

assign select_ln338_15_fu_2654_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_5_0_V_read_4_reg_3107 : trunc_ln708_9_fu_2153_p4);

assign select_ln338_16_fu_2660_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_9_fu_2153_p4 : res_5_1_V_read_4_reg_3102);

assign select_ln338_17_fu_2666_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_6_0_V_read_3_reg_3097 : trunc_ln708_1_fu_2197_p4);

assign select_ln338_18_fu_2672_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_1_fu_2197_p4 : res_6_1_V_read_4_reg_3092);

assign select_ln338_19_fu_2678_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_7_0_V_read_4_reg_3087 : trunc_ln708_2_fu_2238_p4);

assign select_ln338_20_fu_2684_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_2_fu_2238_p4 : res_7_1_V_read_4_reg_3082);

assign select_ln338_21_fu_2690_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_8_0_V_read_4_reg_3077 : trunc_ln708_3_fu_2282_p4);

assign select_ln338_22_fu_2696_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_3_fu_2282_p4 : res_8_1_V_read_3_reg_3072);

assign select_ln338_23_fu_2702_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_9_0_V_read_4_reg_3067 : trunc_ln708_4_fu_2323_p4);

assign select_ln338_24_fu_2708_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_4_fu_2323_p4 : res_9_1_V_read_4_reg_3062);

assign select_ln338_25_fu_2714_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_10_0_V_read_4_reg_3057 : trunc_ln708_10_fu_2367_p4);

assign select_ln338_26_fu_2720_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_10_fu_2367_p4 : res_10_1_V_read_4_reg_3052);

assign select_ln338_27_fu_2726_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_11_0_V_read_3_reg_3047 : trunc_ln708_11_fu_2408_p4);

assign select_ln338_28_fu_2732_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_11_fu_2408_p4 : res_11_1_V_read_4_reg_3042);

assign select_ln338_29_fu_2738_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_12_0_V_read_4_reg_3037 : trunc_ln708_12_fu_2452_p4);

assign select_ln338_30_fu_2744_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_12_fu_2452_p4 : res_12_1_V_read_4_reg_3032);

assign select_ln338_31_fu_2750_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_13_0_V_read_4_reg_3027 : trunc_ln708_13_fu_2493_p4);

assign select_ln338_32_fu_2756_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_13_fu_2493_p4 : res_13_1_V_read_3_reg_3022);

assign select_ln338_33_fu_2762_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_14_0_V_read_4_reg_3017 : trunc_ln708_14_fu_2537_p4);

assign select_ln338_34_fu_2768_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_14_fu_2537_p4 : res_14_1_V_read_4_reg_3012);

assign select_ln338_6_fu_2600_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_s_fu_1939_p4 : res_0_1_V_read_6_reg_3152);

assign select_ln338_7_fu_2606_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_1_0_V_read_5_reg_3147 : trunc_ln708_5_fu_1983_p4);

assign select_ln338_8_fu_2612_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_5_fu_1983_p4 : res_1_1_V_read_5_reg_3142);

assign select_ln338_9_fu_2618_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_2_0_V_read_6_reg_3137 : trunc_ln708_6_fu_2027_p4);

assign select_ln338_fu_2594_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_0_0_V_read_6_reg_3157 : trunc_ln708_s_fu_1939_p4);

assign select_ln708_2_fu_2588_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? trunc_ln708_15_fu_2572_p4 : res_15_1_V_read_4_reg_3002);

assign select_ln708_fu_2582_p3 = ((res_V_offset_read_reg_2966[0:0] === 1'b1) ? res_15_0_V_read_4_reg_3007 : trunc_ln708_15_fu_2572_p4);

assign sext_ln1117_1_fu_1902_p1 = $signed(select_ln1116_17_reg_3162);

assign sext_ln1117_fu_890_p1 = $signed(select_ln1116_fu_882_p3);

assign sext_ln1118_36_fu_912_p1 = $signed(mul_ln1118_fu_906_p2);

assign sext_ln1118_37_fu_962_p1 = select_ln1116_16_fu_954_p3;

assign sext_ln1118_38_fu_972_p1 = $signed(mul_ln1118_28_fu_966_p2);

assign sext_ln1118_39_fu_1014_p1 = $signed(select_ln1117_16_fu_1006_p3);

assign sext_ln1118_40_fu_1024_p1 = $signed(mul_ln1118_29_fu_1018_p2);

assign sext_ln1118_41_fu_1064_p1 = $signed(mul_ln1118_30_fu_1058_p2);

assign sext_ln1118_42_fu_1106_p1 = $signed(select_ln1117_17_fu_1098_p3);

assign sext_ln1118_43_fu_1116_p1 = $signed(mul_ln1118_31_fu_1110_p2);

assign sext_ln1118_44_fu_1156_p1 = $signed(mul_ln1118_32_fu_1150_p2);

assign sext_ln1118_45_fu_1198_p1 = $signed(select_ln1117_18_fu_1190_p3);

assign sext_ln1118_46_fu_1208_p1 = $signed(mul_ln1118_33_fu_1202_p2);

assign sext_ln1118_47_fu_1248_p1 = $signed(mul_ln1118_34_fu_1242_p2);

assign sext_ln1118_48_fu_1290_p1 = $signed(select_ln1117_19_fu_1282_p3);

assign sext_ln1118_49_fu_1300_p1 = $signed(mul_ln1118_35_fu_1294_p2);

assign sext_ln1118_50_fu_1340_p1 = $signed(mul_ln1118_36_fu_1334_p2);

assign sext_ln1118_51_fu_1382_p1 = $signed(select_ln1117_20_fu_1374_p3);

assign sext_ln1118_52_fu_1392_p1 = $signed(mul_ln1118_37_fu_1386_p2);

assign sext_ln1118_53_fu_1432_p1 = $signed(mul_ln1118_38_fu_1426_p2);

assign sext_ln1118_54_fu_1474_p1 = $signed(select_ln1117_21_fu_1466_p3);

assign sext_ln1118_55_fu_1484_p1 = $signed(mul_ln1118_39_fu_1478_p2);

assign sext_ln1118_56_fu_1524_p1 = $signed(mul_ln1118_40_fu_1518_p2);

assign sext_ln1118_58_fu_1576_p1 = $signed(mul_ln1118_41_fu_1570_p2);

assign sext_ln1118_59_fu_1905_p1 = $signed(select_ln1117_23_reg_3167);

assign sext_ln1118_60_fu_1914_p1 = $signed(mul_ln1118_42_fu_1908_p2);

assign sext_ln1118_61_fu_1949_p1 = select_ln1116_18_reg_3177;

assign sext_ln1118_62_fu_1958_p1 = $signed(mul_ln1118_43_fu_1952_p2);

assign sext_ln1118_63_fu_1993_p1 = $signed(select_ln1117_24_reg_3188);

assign sext_ln1118_64_fu_2002_p1 = $signed(mul_ln1118_44_fu_1996_p2);

assign sext_ln1118_65_fu_2043_p1 = $signed(mul_ln1118_45_fu_2037_p2);

assign sext_ln1118_66_fu_2078_p1 = $signed(select_ln1117_25_reg_3203);

assign sext_ln1118_67_fu_2087_p1 = $signed(mul_ln1118_46_fu_2081_p2);

assign sext_ln1118_68_fu_2128_p1 = $signed(mul_ln1118_47_fu_2122_p2);

assign sext_ln1118_69_fu_2163_p1 = $signed(select_ln1117_26_reg_3218);

assign sext_ln1118_70_fu_2172_p1 = $signed(mul_ln1118_48_fu_2166_p2);

assign sext_ln1118_71_fu_2213_p1 = $signed(mul_ln1118_49_fu_2207_p2);

assign sext_ln1118_72_fu_2248_p1 = $signed(select_ln1117_27_reg_3233);

assign sext_ln1118_73_fu_2257_p1 = $signed(mul_ln1118_50_fu_2251_p2);

assign sext_ln1118_74_fu_2298_p1 = $signed(mul_ln1118_51_fu_2292_p2);

assign sext_ln1118_75_fu_2333_p1 = $signed(select_ln1117_28_reg_3248);

assign sext_ln1118_76_fu_2342_p1 = $signed(mul_ln1118_52_fu_2336_p2);

assign sext_ln1118_77_fu_2383_p1 = $signed(mul_ln1118_53_fu_2377_p2);

assign sext_ln1118_78_fu_2418_p1 = $signed(select_ln1117_29_reg_3263);

assign sext_ln1118_79_fu_2427_p1 = $signed(mul_ln1118_54_fu_2421_p2);

assign sext_ln1118_80_fu_2468_p1 = $signed(mul_ln1118_55_fu_2462_p2);

assign sext_ln1118_82_fu_2512_p1 = $signed(mul_ln1118_56_fu_2506_p2);

assign sext_ln1118_fu_902_p1 = $signed(select_ln1117_fu_894_p3);

assign shl_ln728_31_fu_1036_p3 = {{select_ln1265_5_fu_1028_p3}, {20'd0}};

assign shl_ln728_32_fu_1076_p3 = {{select_ln1265_6_fu_1068_p3}, {20'd0}};

assign shl_ln728_33_fu_1128_p3 = {{select_ln1265_7_fu_1120_p3}, {20'd0}};

assign shl_ln728_34_fu_1168_p3 = {{select_ln1265_8_fu_1160_p3}, {20'd0}};

assign shl_ln728_35_fu_1220_p3 = {{select_ln1265_9_fu_1212_p3}, {20'd0}};

assign shl_ln728_36_fu_1260_p3 = {{select_ln1265_10_fu_1252_p3}, {20'd0}};

assign shl_ln728_37_fu_1312_p3 = {{select_ln1265_11_fu_1304_p3}, {20'd0}};

assign shl_ln728_38_fu_1352_p3 = {{select_ln1265_12_fu_1344_p3}, {20'd0}};

assign shl_ln728_39_fu_1404_p3 = {{select_ln1265_13_fu_1396_p3}, {20'd0}};

assign shl_ln728_40_fu_1444_p3 = {{select_ln1265_14_fu_1436_p3}, {20'd0}};

assign shl_ln728_41_fu_1496_p3 = {{select_ln1265_15_fu_1488_p3}, {20'd0}};

assign shl_ln728_42_fu_1536_p3 = {{select_ln1265_16_fu_1528_p3}, {20'd0}};

assign shl_ln728_43_fu_1588_p3 = {{select_ln1265_17_fu_1580_p3}, {20'd0}};

assign shl_ln728_44_fu_1626_p3 = {{select_ln1265_18_fu_1618_p3}, {20'd0}};

assign shl_ln728_45_fu_1918_p3 = {{tmp_reg_3172}, {20'd0}};

assign shl_ln728_46_fu_1962_p3 = {{tmp_s_reg_3183}, {20'd0}};

assign shl_ln728_47_fu_2006_p3 = {{tmp_27_reg_3193}, {20'd0}};

assign shl_ln728_48_fu_2047_p3 = {{tmp_28_reg_3198}, {20'd0}};

assign shl_ln728_49_fu_2091_p3 = {{tmp_29_reg_3208}, {20'd0}};

assign shl_ln728_50_fu_2132_p3 = {{tmp_30_reg_3213}, {20'd0}};

assign shl_ln728_51_fu_2176_p3 = {{tmp_31_reg_3223}, {20'd0}};

assign shl_ln728_52_fu_2217_p3 = {{tmp_32_reg_3228}, {20'd0}};

assign shl_ln728_53_fu_2261_p3 = {{tmp_33_reg_3238}, {20'd0}};

assign shl_ln728_54_fu_2302_p3 = {{tmp_34_reg_3243}, {20'd0}};

assign shl_ln728_55_fu_2346_p3 = {{tmp_35_reg_3253}, {20'd0}};

assign shl_ln728_56_fu_2387_p3 = {{tmp_36_reg_3258}, {20'd0}};

assign shl_ln728_57_fu_2431_p3 = {{tmp_37_reg_3268}, {20'd0}};

assign shl_ln728_58_fu_2472_p3 = {{tmp_38_reg_3273}, {20'd0}};

assign shl_ln728_59_fu_2516_p3 = {{tmp_39_reg_3284}, {20'd0}};

assign shl_ln728_60_fu_2553_p3 = {{tmp_40_reg_3289}, {20'd0}};

assign shl_ln728_s_fu_984_p3 = {{select_ln1265_4_fu_976_p3}, {20'd0}};

assign shl_ln_fu_924_p3 = {{select_ln1265_fu_916_p3}, {20'd0}};

assign trunc_ln1116_1_fu_878_p1 = a_0_0_V_read[31:0];

assign trunc_ln1116_2_fu_946_p1 = a_1_1_V_read[31:0];

assign trunc_ln1116_3_fu_950_p1 = a_1_0_V_read[31:0];

assign trunc_ln1116_4_fu_1646_p1 = a_2_1_V_read[31:0];

assign trunc_ln1116_5_fu_1650_p1 = a_2_0_V_read[31:0];

assign trunc_ln1116_6_fu_1680_p1 = a_3_1_V_read[31:0];

assign trunc_ln1116_7_fu_1684_p1 = a_3_0_V_read[31:0];

assign trunc_ln1116_fu_874_p1 = a_0_1_V_read[31:0];

assign trunc_ln708_10_fu_2367_p4 = {{add_ln1192_57_fu_2361_p2[54:20]}};

assign trunc_ln708_11_fu_2408_p4 = {{add_ln1192_58_fu_2402_p2[54:20]}};

assign trunc_ln708_12_fu_2452_p4 = {{add_ln1192_59_fu_2446_p2[54:20]}};

assign trunc_ln708_13_fu_2493_p4 = {{add_ln1192_60_fu_2487_p2[54:20]}};

assign trunc_ln708_14_fu_2537_p4 = {{add_ln1192_61_fu_2531_p2[54:20]}};

assign trunc_ln708_15_fu_2572_p4 = {{add_ln1192_62_fu_2566_p2[54:20]}};

assign trunc_ln708_1_fu_2197_p4 = {{add_ln1192_53_fu_2191_p2[54:20]}};

assign trunc_ln708_2_fu_2238_p4 = {{add_ln1192_54_fu_2232_p2[54:20]}};

assign trunc_ln708_3_fu_2282_p4 = {{add_ln1192_55_fu_2276_p2[54:20]}};

assign trunc_ln708_4_fu_2323_p4 = {{add_ln1192_56_fu_2317_p2[54:20]}};

assign trunc_ln708_5_fu_1983_p4 = {{add_ln1192_48_fu_1977_p2[54:20]}};

assign trunc_ln708_6_fu_2027_p4 = {{add_ln1192_49_fu_2021_p2[54:20]}};

assign trunc_ln708_7_fu_2068_p4 = {{add_ln1192_50_fu_2062_p2[54:20]}};

assign trunc_ln708_8_fu_2112_p4 = {{add_ln1192_51_fu_2106_p2[54:20]}};

assign trunc_ln708_9_fu_2153_p4 = {{add_ln1192_52_fu_2147_p2[54:20]}};

assign trunc_ln708_s_fu_1939_p4 = {{add_ln1192_47_fu_1933_p2[54:20]}};

assign zext_ln703_24_fu_996_p1 = $unsigned(sext_ln1118_38_fu_972_p1);

assign zext_ln703_25_fu_1048_p1 = $unsigned(sext_ln1118_40_fu_1024_p1);

assign zext_ln703_26_fu_1088_p1 = $unsigned(sext_ln1118_41_fu_1064_p1);

assign zext_ln703_27_fu_1140_p1 = $unsigned(sext_ln1118_43_fu_1116_p1);

assign zext_ln703_28_fu_1180_p1 = $unsigned(sext_ln1118_44_fu_1156_p1);

assign zext_ln703_29_fu_1232_p1 = $unsigned(sext_ln1118_46_fu_1208_p1);

assign zext_ln703_30_fu_1272_p1 = $unsigned(sext_ln1118_47_fu_1248_p1);

assign zext_ln703_31_fu_1324_p1 = $unsigned(sext_ln1118_49_fu_1300_p1);

assign zext_ln703_32_fu_1364_p1 = $unsigned(sext_ln1118_50_fu_1340_p1);

assign zext_ln703_33_fu_1416_p1 = $unsigned(sext_ln1118_52_fu_1392_p1);

assign zext_ln703_34_fu_1456_p1 = $unsigned(sext_ln1118_53_fu_1432_p1);

assign zext_ln703_35_fu_1508_p1 = $unsigned(sext_ln1118_55_fu_1484_p1);

assign zext_ln703_36_fu_1548_p1 = $unsigned(sext_ln1118_56_fu_1524_p1);

assign zext_ln703_37_fu_1600_p1 = $unsigned(sext_ln1118_58_fu_1576_p1);

assign zext_ln703_38_fu_1929_p1 = $unsigned(sext_ln1118_60_fu_1914_p1);

assign zext_ln703_39_fu_1973_p1 = $unsigned(sext_ln1118_62_fu_1958_p1);

assign zext_ln703_40_fu_2017_p1 = $unsigned(sext_ln1118_64_fu_2002_p1);

assign zext_ln703_41_fu_2058_p1 = $unsigned(sext_ln1118_65_fu_2043_p1);

assign zext_ln703_42_fu_2102_p1 = $unsigned(sext_ln1118_67_fu_2087_p1);

assign zext_ln703_43_fu_2143_p1 = $unsigned(sext_ln1118_68_fu_2128_p1);

assign zext_ln703_44_fu_2187_p1 = $unsigned(sext_ln1118_70_fu_2172_p1);

assign zext_ln703_45_fu_2228_p1 = $unsigned(sext_ln1118_71_fu_2213_p1);

assign zext_ln703_46_fu_2272_p1 = $unsigned(sext_ln1118_73_fu_2257_p1);

assign zext_ln703_47_fu_2313_p1 = $unsigned(sext_ln1118_74_fu_2298_p1);

assign zext_ln703_48_fu_2357_p1 = $unsigned(sext_ln1118_76_fu_2342_p1);

assign zext_ln703_49_fu_2398_p1 = $unsigned(sext_ln1118_77_fu_2383_p1);

assign zext_ln703_50_fu_2442_p1 = $unsigned(sext_ln1118_79_fu_2427_p1);

assign zext_ln703_51_fu_2483_p1 = $unsigned(sext_ln1118_80_fu_2468_p1);

assign zext_ln703_52_fu_2527_p1 = $unsigned(sext_ln1118_82_fu_2512_p1);

assign zext_ln703_fu_936_p1 = $unsigned(sext_ln1118_36_fu_912_p1);

assign zext_ln728_24_fu_992_p1 = shl_ln728_s_fu_984_p3;

assign zext_ln728_25_fu_1044_p1 = shl_ln728_31_fu_1036_p3;

assign zext_ln728_26_fu_1084_p1 = shl_ln728_32_fu_1076_p3;

assign zext_ln728_27_fu_1136_p1 = shl_ln728_33_fu_1128_p3;

assign zext_ln728_28_fu_1176_p1 = shl_ln728_34_fu_1168_p3;

assign zext_ln728_29_fu_1228_p1 = shl_ln728_35_fu_1220_p3;

assign zext_ln728_30_fu_1268_p1 = shl_ln728_36_fu_1260_p3;

assign zext_ln728_31_fu_1320_p1 = shl_ln728_37_fu_1312_p3;

assign zext_ln728_32_fu_1360_p1 = shl_ln728_38_fu_1352_p3;

assign zext_ln728_33_fu_1412_p1 = shl_ln728_39_fu_1404_p3;

assign zext_ln728_34_fu_1452_p1 = shl_ln728_40_fu_1444_p3;

assign zext_ln728_35_fu_1504_p1 = shl_ln728_41_fu_1496_p3;

assign zext_ln728_36_fu_1544_p1 = shl_ln728_42_fu_1536_p3;

assign zext_ln728_37_fu_1596_p1 = shl_ln728_43_fu_1588_p3;

assign zext_ln728_38_fu_1925_p1 = shl_ln728_45_fu_1918_p3;

assign zext_ln728_39_fu_1969_p1 = shl_ln728_46_fu_1962_p3;

assign zext_ln728_40_fu_2013_p1 = shl_ln728_47_fu_2006_p3;

assign zext_ln728_41_fu_2054_p1 = shl_ln728_48_fu_2047_p3;

assign zext_ln728_42_fu_2098_p1 = shl_ln728_49_fu_2091_p3;

assign zext_ln728_43_fu_2139_p1 = shl_ln728_50_fu_2132_p3;

assign zext_ln728_44_fu_2183_p1 = shl_ln728_51_fu_2176_p3;

assign zext_ln728_45_fu_2224_p1 = shl_ln728_52_fu_2217_p3;

assign zext_ln728_46_fu_2268_p1 = shl_ln728_53_fu_2261_p3;

assign zext_ln728_47_fu_2309_p1 = shl_ln728_54_fu_2302_p3;

assign zext_ln728_48_fu_2353_p1 = shl_ln728_55_fu_2346_p3;

assign zext_ln728_49_fu_2394_p1 = shl_ln728_56_fu_2387_p3;

assign zext_ln728_50_fu_2438_p1 = shl_ln728_57_fu_2431_p3;

assign zext_ln728_51_fu_2479_p1 = shl_ln728_58_fu_2472_p3;

assign zext_ln728_52_fu_2523_p1 = shl_ln728_59_fu_2516_p3;

assign zext_ln728_fu_932_p1 = shl_ln_fu_924_p3;

endmodule //matmul_ap_fixed_ap_fixed_2ul_2ul_2ul_8ul_s
